// src/native/core/svelte/date-range-input/DateRangeInput.svelte
<script lang="ts">
    import { DateRangeInputStore } from "../../design-core";
    import type { DateRangeInputState } from "../../design-core";
    import { dateRangeInput as cls } from "../../../styles";
    import CalendarManager from "./CalendarManager.svelte";
    import StandaloneDateInput from "./StandaloneDateInput.svelte";
    import type { DateRangeValue } from "./types";
    import { onMount } from "svelte";

    interface Props {
        startDate?: string;
        endDate?: string;
        minDate?: string;
        maxDate?: string;
        disabledDates?: string[];
        disabled?: boolean;
        error?: boolean;
        label?: string;
        onchange?: (value: DateRangeValue) => void;
    }

    let {
        startDate = "",
        endDate = "",
        minDate,
        maxDate,
        disabledDates,
        disabled = false,
        error = false,
        label,
        onchange,
    }: Props = $props();

    const store = new DateRangeInputStore(
        {
            variant: "range",
            numberOfDays: 1,
            withButton: true,
            readOnly: false,
            disabled: false,
            allowDisabledSelection: false,
        },
        {}
    );

    let storeState: DateRangeInputState = $state(store.getState());

    $effect(() => {
        return store.subscribe(() => {
            storeState = store.getState();
        });
    });

    $effect(() => {
        store.syncValues(startDate, endDate);
    });

    $effect(() => {
        store.updateConfig({ disabled, disabledDates, minDate, maxDate });
    });

    $effect(() => {
        store.updateCallbacks({
            onChange: (s, e) => onchange?.({ start: s, end: e }),
        });
    });

    let wrapperEl: HTMLDivElement | undefined = $state();
    let startInputRef: StandaloneDateInput | undefined = $state();
    let endInputRef: StandaloneDateInput | undefined = $state();
    let calendarManagerRef: CalendarManager | undefined = $state();

    $effect(() => {
        if (calendarManagerRef) {
            store.setCalendarRef({
                setCalendarDate: (val) => calendarManagerRef!.setCalendarDateTo(val),
            });
        }
    });

    $effect(() => {
        if (startInputRef) {
            store.setStartInputRef({
                resetPlaceholder: () => startInputRef!.resetPlaceholder(),
                resetInput: () => startInputRef!.resetInput(),
                focusYearRef: () => startInputRef!.focusYear(),
            });
        }
    });

    $effect(() => {
        if (endInputRef) {
            store.setEndInputRef({
                resetPlaceholder: () => endInputRef!.resetPlaceholder(),
                resetInput: () => endInputRef!.resetInput(),
                focusYearRef: () => endInputRef!.focusYear(),
            });
        }
    });

    let doneButtonDisabled = $derived(!storeState.selectedStart || !storeState.selectedEnd);
    let isStartFocused = $derived(storeState.currentFocus === "start");
    let isEndFocused = $derived(storeState.currentFocus === "end");

    let containerClasses = $derived.by(() => {
        const classes: string[] = [cls.container];
        if (storeState.focused) classes.push(cls.containerFocused);
        if (disabled) classes.push(cls.containerDisabled);
        if (error) classes.push(cls.containerError);
        return classes.join(" ");
    });

    function handleOutsideClick(event: MouseEvent) {
        if (!wrapperEl) return;
        if (wrapperEl.contains(event.target as Node)) return;
        if (storeState.calendarOpen) {
            store.handleCalendarDismiss("reset");
        }
    }

    onMount(() => {
        document.addEventListener("mousedown", handleOutsideClick);
        return () => {
            document.removeEventListener("mousedown", handleOutsideClick);
        };
    });

    function handleInputWrapperClick() {
        if (disabled) return;
        if (!storeState.calendarOpen) {
            store.handleFocus();
        }
    }

    function handleStartChange(val: string) {
        store.handleStartDateChange(val);
    }

    function handleEndChange(val: string) {
        store.handleEndDateChange(val);
    }

    function handleStartFocus() {
        store.handleInputFocus("start");
    }

    function handleEndFocus() {
        store.handleInputFocus("end");
    }

    function handleStartBlur(valid: boolean) {
        store.handleStartInputBlur(valid);
    }

    function handleEndBlur(valid: boolean) {
        store.handleEndInputBlur(valid);
    }

    function handleDaySelect(date: import("dayjs").Dayjs) {
        store.handleCalendarSelect(date.format("YYYY-MM-DD"));
    }

    function handleDayHover(dateStr: string) {
        store.handleCalendarHover(dateStr);
    }

    function handleDismiss(action: "reset" | "confirmed") {
        store.handleCalendarDismiss(action);
    }
</script>

<div bind:this={wrapperEl} class={cls.root} style="position: relative; max-width: 400px;">
    {#if label}
        <label
            style="display: block; font-size: 14px; font-weight: 600; color: var(--fds-colour-text); margin-bottom: 8px;"
        >
            {label}
        </label>
    {/if}

    <!-- svelte-ignore a11y_click_events_have_key_events -->
    <!-- svelte-ignore a11y_no_static_element_interactions -->
    <div class={containerClasses} onclick={handleInputWrapperClick}>
        <StandaloneDateInput
            bind:this={startInputRef}
            side="start"
            value={storeState.selectedStart}
            focused={isStartFocused}
            {disabled}
            label="Start date"
            onchange={handleStartChange}
            onfocus={handleStartFocus}
            onblur={handleStartBlur}
        />
        <span class={cls.separator}>to</span>
        <StandaloneDateInput
            bind:this={endInputRef}
            side="end"
            value={storeState.selectedEnd}
            focused={isEndFocused}
            {disabled}
            label="End date"
            onchange={handleEndChange}
            onfocus={handleEndFocus}
            onblur={handleEndBlur}
        />
    </div>

    {#if storeState.calendarOpen && !disabled}
        <div class={cls.dropdown}>
            <CalendarManager
                bind:this={calendarManagerRef}
                initialCalendarDate={storeState.initialCalendarDate}
                startDate={storeState.selectedStart}
                endDate={storeState.selectedEnd}
                currentFocus={storeState.currentFocus}
                hoverDate={storeState.hoverValue ?? ""}
                {minDate}
                {maxDate}
                {disabledDates}
                withButton={true}
                {doneButtonDisabled}
                ondismiss={handleDismiss}
                onselectday={handleDaySelect}
                onhoverday={handleDayHover}
            />
        </div>
    {/if}
</div>

// src/native/core/vue/date-range-input/DateRangeInput.vue
<script setup lang="ts">
import type { Dayjs } from "dayjs";
import dayjs from "dayjs";
import {
    computed,
    onBeforeUnmount,
    onMounted,
    ref,
    shallowRef,
    watch,
} from "vue";
import { dateRangeInput as cls } from "../../../styles";
import { DateRangeInputStore } from "../../design-core";
import type { InputRefActions, CalendarRefActions } from "../../design-core";
import CalendarManager from "./CalendarManager.vue";
import StandaloneDateInput from "./StandaloneDateInput.vue";
import type { CalendarAction, DateRangeValue } from "./types";

const props = withDefaults(
    defineProps<{
        startDate?: string;
        endDate?: string;
        minDate?: string;
        maxDate?: string;
        disabledDates?: string[];
        disabled?: boolean;
        error?: boolean;
        label?: string;
    }>(),
    {
        startDate: "",
        endDate: "",
        disabled: false,
        error: false,
    }
);

const emit = defineEmits<{
    change: [value: DateRangeValue];
}>();

// =============================================================================
// STORE
// =============================================================================

const store = new DateRangeInputStore(
    {
        variant: "range",
        numberOfDays: 7,
        withButton: true,
        readOnly: false,
        disabled: props.disabled,
        allowDisabledSelection: false,
        disabledDates: props.disabledDates,
        minDate: props.minDate,
        maxDate: props.maxDate,
    },
    {
        onChange: (start, end) => emit("change", { start, end }),
    }
);

const state = shallowRef(store.getState());
const unsubscribe = store.subscribe(() => {
    state.value = store.getState();
});

onBeforeUnmount(() => {
    unsubscribe();
});

// =============================================================================
// SYNC PROPS -> STORE
// =============================================================================

watch(
    () => [props.startDate, props.endDate],
    ([s, e]) => store.syncValues(s, e),
    { immediate: true }
);

watch(
    () => [props.disabled, props.disabledDates, props.minDate, props.maxDate],
    () => {
        store.updateConfig({
            disabled: props.disabled,
            disabledDates: props.disabledDates,
            minDate: props.minDate,
            maxDate: props.maxDate,
        });
    }
);

// =============================================================================
// REFS
// =============================================================================

const wrapperRef = ref<HTMLDivElement | null>(null);
const startInputRef = ref<InstanceType<typeof StandaloneDateInput> | null>(
    null
);
const endInputRef = ref<InstanceType<typeof StandaloneDateInput> | null>(null);
const calendarManagerRef = ref<InstanceType<typeof CalendarManager> | null>(
    null
);

function wrapStartInputRef(): InputRefActions {
    return {
        resetPlaceholder: () => startInputRef.value?.resetInput(),
        resetInput: () => startInputRef.value?.resetInput(),
        focusYearRef: () => startInputRef.value?.focusDay(),
    };
}

function wrapEndInputRef(): InputRefActions {
    return {
        resetPlaceholder: () => endInputRef.value?.resetInput(),
        resetInput: () => endInputRef.value?.resetInput(),
        focusYearRef: () => endInputRef.value?.focusDay(),
    };
}

function wrapCalendarRef(): CalendarRefActions {
    return {
        setCalendarDate: (val: string) =>
            calendarManagerRef.value?.setCalendarDateTo(val),
    };
}

onMounted(() => {
    store.setStartInputRef(wrapStartInputRef());
    store.setEndInputRef(wrapEndInputRef());
    store.setCalendarRef(wrapCalendarRef());
    document.addEventListener("mousedown", handleOutsideClick);
});

onBeforeUnmount(() => {
    document.removeEventListener("mousedown", handleOutsideClick);
});

// =============================================================================
// COMPUTED
// =============================================================================

const isStartFocused = computed(() => state.value.currentFocus === "start");
const isEndFocused = computed(() => state.value.currentFocus === "end");

const containerClasses = computed(() => {
    const classes: string[] = [cls.container];
    if (state.value.focused) classes.push(cls.containerFocused);
    if (props.disabled) classes.push(cls.containerDisabled);
    if (props.error) classes.push(cls.containerError);
    return classes;
});

const calendarInitialDate = computed(() => state.value.initialCalendarDate);

const doneButtonDisabled = computed(() => {
    const s = state.value;
    if (!s.selectedStart || !s.selectedEnd) return true;
    if (dayjs(s.selectedStart).isAfter(s.selectedEnd, "day")) return true;
    return false;
});

// =============================================================================
// HANDLERS (thin wrappers delegating to store)
// =============================================================================

function handleOutsideClick(event: MouseEvent) {
    if (!wrapperRef.value) return;
    if (wrapperRef.value.contains(event.target as Node)) return;

    if (state.value.calendarOpen || state.value.focused) {
        store.handleBlur(true);
    }
}

function handleInputWrapperClick() {
    if (props.disabled) return;
    store.handleFocus();
}

function handleStartFocus() {
    store.handleInputFocus("start");
}

function handleEndFocus() {
    store.handleInputFocus("end");
}

function handleStartChange(value: string) {
    store.handleStartDateChange(value);
}

function handleEndChange(value: string) {
    store.handleEndDateChange(value);
}

function handleStartBlur(valid: boolean) {
    store.handleStartInputBlur(valid);
}

function handleEndBlur(valid: boolean) {
    store.handleEndInputBlur(valid);
}

function handleDaySelect(date: Dayjs) {
    const dateStr = date.format("YYYY-MM-DD");
    store.handleCalendarSelect(dateStr);
}

function handleDayHover(dateStr: string) {
    store.handleCalendarHover(dateStr);
}

function handleDismiss(action: CalendarAction) {
    store.handleCalendarDismiss(action);
}
</script>

<template>
    <div
        ref="wrapperRef"
        :class="cls.root"
        style="position: relative; max-width: 400px"
    >
        <!-- Label -->
        <label
            v-if="label"
            style="
                display: block;
                font-size: 14px;
                font-weight: 600;
                color: var(--fds-colour-text);
                margin-bottom: 8px;
            "
        >
            {{ label }}
        </label>

        <!-- Input row -->
        <div :class="containerClasses" @click="handleInputWrapperClick">
            <StandaloneDateInput
                ref="startInputRef"
                side="start"
                :value="state.selectedStart"
                :focused="isStartFocused"
                :disabled="disabled"
                label="Start date"
                @change="handleStartChange"
                @focus="handleStartFocus"
                @blur="handleStartBlur"
            />
            <span :class="cls.separator">to</span>
            <StandaloneDateInput
                ref="endInputRef"
                side="end"
                :value="state.selectedEnd"
                :focused="isEndFocused"
                :disabled="disabled"
                label="End date"
                @change="handleEndChange"
                @focus="handleEndFocus"
                @blur="handleEndBlur"
            />
        </div>

        <!-- Calendar dropdown -->
        <div v-if="state.calendarOpen && !disabled" :class="cls.dropdown">
            <CalendarManager
                ref="calendarManagerRef"
                :initial-calendar-date="calendarInitialDate"
                :start-date="state.selectedStart"
                :end-date="state.selectedEnd"
                :current-focus="state.currentFocus"
                :hover-date="state.hoverValue || ''"
                :min-date="minDate"
                :max-date="maxDate"
                :disabled-dates="disabledDates"
                :with-button="true"
                :done-button-disabled="doneButtonDisabled"
                @dismiss="handleDismiss"
                @select-day="handleDaySelect"
                @hover-day="handleDayHover"
            />
        </div>
    </div>
</template>
