// src/native/core/react-native/date-range-input/DateRangeInputV2.tsx
/**
 * DateRangeInputV2 — React Native port consuming @lifesg/design-core store.
 *
 * Full parity with the React DateRangeInput:
 *   - 3 variants: range, week, fixed-range
 *   - dirty tracking (isStartDirty / isEndDirty)
 *   - unselectable validation (disabled dates, min/max)
 *   - hover preview in inputs (calendar hover → input overlay)
 *   - blur / dismiss / cancel distinction
 *   - withButton toggle
 *   - focus management
 */
import React, {
    useCallback,
    useEffect,
    useMemo,
    useRef,
    useSyncExternalStore,
} from "react";
import { Pressable, Text, View } from "react-native";

import { DateRangeInputStore } from "../../design-core";
import type {
    DateRangeVariant,
    FocusType,
    InputRefActions,
    CalendarRefActions,
} from "../../design-core";
import dayjs from "dayjs";
import { dateRangeInputStyles as s } from "./styles";
import { StandaloneDateInput } from "./StandaloneDateInput";
import { CalendarManager } from "./CalendarManager";
import { CalendarBottomSheet } from "./CalendarBottomSheet";

// =============================================================================
// PROPS
// =============================================================================

export interface DateRangeInputV2Props {
    value?: string;
    valueEnd?: string;
    minDate?: string;
    maxDate?: string;
    disabledDates?: string[];
    disabled?: boolean;
    readOnly?: boolean;
    error?: boolean;
    variant?: DateRangeVariant;
    numberOfDays?: number;
    withButton?: boolean;
    allowDisabledSelection?: boolean;
    onChange?: (startDate: string, endDate: string) => void;
    onFocus?: () => void;
    onBlur?: () => void;
}

// =============================================================================
// HOOK — bridge design-core Store to React via useSyncExternalStore
// =============================================================================

function useStore(store: DateRangeInputStore) {
    return useSyncExternalStore(
        useCallback((cb) => store.subscribe(cb), [store]),
        useCallback(() => store.getState(), [store])
    );
}

// =============================================================================
// COMPONENT
// =============================================================================

export function DateRangeInputV2({
    value = "",
    valueEnd = "",
    minDate,
    maxDate,
    disabledDates,
    disabled = false,
    readOnly = false,
    error = false,
    variant = "range",
    numberOfDays = 7,
    withButton = true,
    allowDisabledSelection = false,
    onChange,
    onFocus,
    onBlur,
}: DateRangeInputV2Props) {
    // ---- store ----
    const storeRef = useRef<DateRangeInputStore | null>(null);
    if (!storeRef.current) {
        storeRef.current = new DateRangeInputStore(
            {
                variant,
                numberOfDays,
                withButton,
                readOnly,
                disabled,
                allowDisabledSelection,
                disabledDates,
                minDate,
                maxDate,
            },
            { onChange, onFocus, onBlur }
        );
    }
    const store = storeRef.current;
    const state = useStore(store);

    // ---- sync props → store ----
    useEffect(() => {
        store.syncValues(value, valueEnd);
    }, [value, valueEnd]);

    useEffect(() => {
        store.updateConfig({
            variant,
            numberOfDays,
            withButton,
            readOnly,
            disabled,
            allowDisabledSelection,
            disabledDates,
            minDate,
            maxDate,
        });
    }, [
        variant,
        numberOfDays,
        withButton,
        readOnly,
        disabled,
        allowDisabledSelection,
        disabledDates,
        minDate,
        maxDate,
    ]);

    useEffect(() => {
        store.updateCallbacks({ onChange, onFocus, onBlur });
    }, [onChange, onFocus, onBlur]);

    // ---- imperative refs ----
    const startInputRef = useRef<any>(null);
    const endInputRef = useRef<any>(null);
    const calendarManagerRef = useRef<any>(null);

    useEffect(() => {
        store.setStartInputRef({
            resetPlaceholder: () => startInputRef.current?.resetInput?.(),
            resetInput: () => startInputRef.current?.resetInput?.(),
            focusYearRef: () => startInputRef.current?.focusYear?.(),
        });
        store.setEndInputRef({
            resetPlaceholder: () => endInputRef.current?.resetInput?.(),
            resetInput: () => endInputRef.current?.resetInput?.(),
            focusYearRef: () => endInputRef.current?.focusYear?.(),
        });
        store.setCalendarRef({
            setCalendarDate: (val: string) =>
                calendarManagerRef.current?.setCalendarDate?.(val),
        });
    }, []);

    // ---- handlers ----
    const handleFocus = useCallback(
        (focus: FocusType) => {
            if (disabled || readOnly) return;
            store.handleInputFocus(focus);
        },
        [disabled, readOnly]
    );

    const handleStartChange = useCallback(
        (val: string) => {
            const handler = store.getStartInputHandler();
            handler(val);
        },
        [variant]
    );

    const handleEndChange = useCallback((val: string) => {
        store.handleEndDateChange(val);
    }, []);

    const handleDaySelect = useCallback((date: string) => {
        store.handleCalendarSelect(date);
    }, []);

    const handleDismiss = useCallback((action: "reset" | "confirmed") => {
        store.handleCalendarDismiss(action);
    }, []);

    const handleCalendarHover = useCallback((val: string) => {
        store.handleCalendarHover(val);
    }, []);

    // ---- derived ----
    const bothFilled =
        state.selectedStart &&
        state.selectedEnd &&
        dayjs(state.selectedStart, "YYYY-MM-DD", true).isValid() &&
        dayjs(state.selectedEnd, "YYYY-MM-DD", true).isValid();

    const doneDisabled = !bothFilled;

    const containerStyle = [
        s.container,
        state.calendarOpen && s.containerFocused,
        disabled && s.containerDisabled,
        error && s.containerError,
    ];

    const isWeek = variant === "week";
    const isFixed = variant === "fixed-range";

    return (
        <View>
            <Pressable
                style={containerStyle}
                onPress={() => {
                    if (!disabled && !readOnly) {
                        store.handleFocus();
                    }
                }}
            >
                <StandaloneDateInput
                    ref={startInputRef}
                    value={state.selectedStart}
                    label="Start date"
                    disabled={disabled || state.isStartDisabled}
                    focused={state.currentFocus === "start"}
                    onChange={handleStartChange}
                    onFocus={() => handleFocus("start")}
                />
                <Text style={s.separator}>–</Text>
                <StandaloneDateInput
                    ref={endInputRef}
                    value={state.selectedEnd}
                    label="End date"
                    disabled={disabled || state.isEndDisabled}
                    focused={state.currentFocus === "end"}
                    onChange={handleEndChange}
                    onFocus={() => handleFocus("end")}
                />
            </Pressable>

            <CalendarBottomSheet
                visible={state.calendarOpen && !disabled && !readOnly}
                onClose={() => store.handleCalendarDismiss("reset")}
            >
                <CalendarManager
                    calendarDate={
                        state.initialCalendarDate ||
                        state.selectedStart ||
                        dayjs().format("YYYY-MM-DD")
                    }
                    selectedStart={state.selectedStart}
                    selectedEnd={state.selectedEnd}
                    minDate={minDate}
                    maxDate={maxDate}
                    disabledDates={disabledDates}
                    withButton={withButton}
                    doneDisabled={doneDisabled}
                    variant={variant}
                    numberOfDays={numberOfDays}
                    currentFocus={state.currentFocus}
                    selectWithinRange={state.isStartDirty || state.isEndDirty}
                    allowDisabledSelection={allowDisabledSelection}
                    onSelect={handleDaySelect}
                    onDismiss={handleDismiss}
                    onHover={handleCalendarHover}
                />
            </CalendarBottomSheet>
        </View>
    );
}

// src/native/core/vue/date-range-input/DateRangeInputV2.vue
<script setup lang="ts">
/**
 * DateRangeInputV2 — Vue 3 port consuming @lifesg/design-core store.
 *
 * Full parity with the React DateRangeInput:
 *   - 3 variants: range, week, fixed-range
 *   - dirty tracking (isStartDirty / isEndDirty)
 *   - unselectable validation (disabled dates, min/max)
 *   - hover preview in inputs
 *   - blur / dismiss / cancel distinction
 *   - withButton toggle
 *   - focus management
 */
import dayjs from "dayjs";
import type { Dayjs } from "dayjs";
import {
    computed,
    nextTick,
    onBeforeUnmount,
    onMounted,
    ref,
    shallowRef,
    watch,
} from "vue";
import { dateRangeInput as cls } from "../../../styles";
import { DateRangeInputStore } from "../../design-core";
import type {
    DateRangeVariant,
    FocusType,
    InputRefActions,
    CalendarRefActions,
} from "../../design-core";
import CalendarManager from "./CalendarManager.vue";
import StandaloneDateInput from "./StandaloneDateInput.vue";
import type { CalendarAction, DateRangeValue } from "./types";

// =============================================================================
// PROPS & EMIT
// =============================================================================

const props = withDefaults(
    defineProps<{
        startDate?: string;
        endDate?: string;
        minDate?: string;
        maxDate?: string;
        disabledDates?: string[];
        disabled?: boolean;
        readOnly?: boolean;
        error?: boolean;
        label?: string;
        variant?: DateRangeVariant;
        numberOfDays?: number;
        withButton?: boolean;
        allowDisabledSelection?: boolean;
    }>(),
    {
        startDate: "",
        endDate: "",
        disabled: false,
        readOnly: false,
        error: false,
        variant: "range",
        numberOfDays: 7,
        withButton: true,
        allowDisabledSelection: false,
    }
);

const emit = defineEmits<{
    change: [value: DateRangeValue];
    focus: [];
    blur: [];
}>();

// =============================================================================
// STORE
// =============================================================================

const store = new DateRangeInputStore(
    {
        variant: props.variant,
        numberOfDays: props.numberOfDays,
        withButton: props.withButton,
        readOnly: props.readOnly,
        disabled: props.disabled,
        allowDisabledSelection: props.allowDisabledSelection,
        disabledDates: props.disabledDates,
        minDate: props.minDate,
        maxDate: props.maxDate,
    },
    {
        onChange: (start, end) => emit("change", { start, end }),
        onFocus: () => emit("focus"),
        onBlur: () => emit("blur"),
    }
);

const state = shallowRef(store.getState());
const unsubscribe = store.subscribe(() => {
    state.value = store.getState();
});

onBeforeUnmount(() => {
    unsubscribe();
});

// =============================================================================
// SYNC PROPS → STORE
// =============================================================================

watch(
    () => [props.startDate, props.endDate],
    ([s, e]) => store.syncValues(s, e),
    { immediate: true }
);

watch(
    () => [
        props.variant,
        props.numberOfDays,
        props.withButton,
        props.readOnly,
        props.disabled,
        props.allowDisabledSelection,
        props.disabledDates,
        props.minDate,
        props.maxDate,
    ],
    () => {
        store.updateConfig({
            variant: props.variant,
            numberOfDays: props.numberOfDays,
            withButton: props.withButton,
            readOnly: props.readOnly,
            disabled: props.disabled,
            allowDisabledSelection: props.allowDisabledSelection,
            disabledDates: props.disabledDates,
            minDate: props.minDate,
            maxDate: props.maxDate,
        });
    }
);

// =============================================================================
// REFS
// =============================================================================

const wrapperRef = ref<HTMLDivElement | null>(null);
const startInputRef = ref<InstanceType<typeof StandaloneDateInput> | null>(
    null
);
const endInputRef = ref<InstanceType<typeof StandaloneDateInput> | null>(null);
const calendarManagerRef = ref<InstanceType<typeof CalendarManager> | null>(
    null
);

function wrapStartInputRef(): InputRefActions {
    return {
        resetPlaceholder: () => startInputRef.value?.resetInput(),
        resetInput: () => startInputRef.value?.resetInput(),
        focusYearRef: () => startInputRef.value?.focusDay(),
    };
}

function wrapEndInputRef(): InputRefActions {
    return {
        resetPlaceholder: () => endInputRef.value?.resetInput(),
        resetInput: () => endInputRef.value?.resetInput(),
        focusYearRef: () => endInputRef.value?.focusDay(),
    };
}

function wrapCalendarRef(): CalendarRefActions {
    return {
        setCalendarDate: (val: string) =>
            calendarManagerRef.value?.setCalendarDateTo(val),
    };
}

onMounted(() => {
    store.setStartInputRef(wrapStartInputRef());
    store.setEndInputRef(wrapEndInputRef());
    store.setCalendarRef(wrapCalendarRef());
    document.addEventListener("mousedown", handleOutsideClick);
});

onBeforeUnmount(() => {
    document.removeEventListener("mousedown", handleOutsideClick);
});

// =============================================================================
// COMPUTED
// =============================================================================

const isStartFocused = computed(() => state.value.currentFocus === "start");
const isEndFocused = computed(() => state.value.currentFocus === "end");

const containerClasses = computed(() => {
    const classes: string[] = [cls.container];
    if (state.value.focused) classes.push(cls.containerFocused);
    if (props.disabled) classes.push(cls.containerDisabled);
    if (props.error) classes.push(cls.containerError);
    return classes;
});

const calendarInitialDate = computed(() => state.value.initialCalendarDate);

const doneButtonDisabled = computed(() => {
    const s = state.value;
    if (!s.selectedStart || !s.selectedEnd) return true;
    if (dayjs(s.selectedStart).isAfter(s.selectedEnd, "day")) return true;
    return false;
});

const startHoverValue = computed(() => store.getHoverValue("start"));
const endHoverValue = computed(() => store.getHoverValue("end"));

const startInputReadOnly = computed(
    () => state.value.isStartDisabled || props.readOnly
);
const endInputReadOnly = computed(
    () => state.value.isEndDisabled || props.readOnly
);

const selectWithinRange = computed(() => store.getSelectWithinRange());

// =============================================================================
// HANDLERS (thin wrappers delegating to store)
// =============================================================================

function handleOutsideClick(event: MouseEvent) {
    if (!wrapperRef.value) return;
    if (wrapperRef.value.contains(event.target as Node)) return;

    if (state.value.calendarOpen || state.value.focused) {
        store.handleBlur(true);
    }
}

function handleInputWrapperClick() {
    if (props.disabled || props.readOnly) return;
    store.handleFocus();
}

function handleStartFocus() {
    store.handleInputFocus("start");
}

function handleEndFocus() {
    store.handleInputFocus("end");
}

function handleStartChange(value: string) {
    const handler = store.getStartInputHandler();
    handler(value);
}

function handleEndChange(value: string) {
    store.handleEndDateChange(value);
}

function handleStartBlur(valid: boolean) {
    store.handleStartInputBlur(valid);
}

function handleEndBlur(valid: boolean) {
    store.handleEndInputBlur(valid);
}

function handleDaySelect(date: Dayjs) {
    const dateStr = date.format("YYYY-MM-DD");
    store.handleCalendarSelect(dateStr);
}

function handleDayHover(dateStr: string) {
    store.handleCalendarHover(dateStr);
}

function handleDismiss(action: CalendarAction) {
    store.handleCalendarDismiss(action);
}

function handleNodeKeyDown(event: KeyboardEvent) {
    store.handleNodeKeyDown(event.code);
}
</script>

<template>
    <div
        ref="wrapperRef"
        :class="cls.root"
        style="position: relative; max-width: 400px"
    >
        <!-- Label -->
        <label
            v-if="label"
            style="
                display: block;
                font-size: 14px;
                font-weight: 600;
                color: var(--fds-colour-text);
                margin-bottom: 8px;
            "
        >
            {{ label }}
        </label>

        <!-- Input row -->
        <div
            :class="containerClasses"
            @click="handleInputWrapperClick"
            @keydown="handleNodeKeyDown"
            tabindex="0"
        >
            <StandaloneDateInput
                ref="startInputRef"
                side="start"
                :value="state.selectedStart"
                :focused="isStartFocused"
                :disabled="disabled"
                :read-only="startInputReadOnly"
                :hover-value="startHoverValue"
                label="Start date"
                @change="handleStartChange"
                @focus="handleStartFocus"
                @blur="handleStartBlur"
            />
            <span :class="cls.separator">to</span>
            <StandaloneDateInput
                ref="endInputRef"
                side="end"
                :value="state.selectedEnd"
                :focused="isEndFocused"
                :disabled="disabled"
                :read-only="endInputReadOnly"
                :hover-value="endHoverValue"
                label="End date"
                @change="handleEndChange"
                @focus="handleEndFocus"
                @blur="handleEndBlur"
            />
        </div>

        <!-- Calendar dropdown -->
        <div
            v-if="state.calendarOpen && !disabled && !readOnly"
            :class="cls.dropdown"
        >
            <CalendarManager
                ref="calendarManagerRef"
                :initial-calendar-date="calendarInitialDate"
                :start-date="state.selectedStart"
                :end-date="state.selectedEnd"
                :current-focus="state.currentFocus"
                :hover-date="state.hoverValue || ''"
                :min-date="minDate"
                :max-date="maxDate"
                :disabled-dates="disabledDates"
                :with-button="withButton"
                :done-button-disabled="doneButtonDisabled"
                :select-within-range="selectWithinRange"
                :variant="variant"
                :number-of-days="numberOfDays"
                :allow-disabled-selection="allowDisabledSelection"
                @dismiss="handleDismiss"
                @select-day="handleDaySelect"
                @hover-day="handleDayHover"
            />
        </div>
    </div>
</template>
