// native-ports/shared-core/ui/svelte/src/button/Button.svelte
<script lang="ts">
    import type { Snippet } from "svelte";
    import { button as cls } from "@lifesg/flagship-styles";
    import { getButtonClasses } from "@lifesg/design-core";
    import type { ButtonIconPosition, ButtonSizeType, ButtonStyleType } from "@lifesg/design-core";
    import LoadingSpinner from "./LoadingSpinner.svelte";

    interface Props {
        styleType?: ButtonStyleType;
        sizeType?: ButtonSizeType;
        danger?: boolean;
        loading?: boolean;
        disabled?: boolean;
        focusableWhenDisabled?: boolean;
        iconPosition?: ButtonIconPosition;
        type?: "button" | "submit" | "reset";
        "aria-label"?: string;
        onclick?: (event: MouseEvent) => void;
        icon?: Snippet;
        children?: Snippet;
    }

    let {
        styleType = "default",
        sizeType = "default",
        danger = false,
        loading = false,
        disabled = false,
        focusableWhenDisabled = false,
        iconPosition = "left",
        type = "button",
        "aria-label": ariaLabel,
        onclick,
        icon,
        children,
    }: Props = $props();

    let hasIcon = $derived(!!icon);
    let hasChildren = $derived(!!children);
    let isIconOnly = $derived(hasIcon && !hasChildren);

    let buttonClasses = $derived(
        getButtonClasses({
            styleType,
            sizeType,
            danger,
            disabled,
            focusableWhenDisabled,
            iconOnly: isIconOnly,
            iconPosition,
            hasChildren,
        })
    );

    let isDisabled = $derived(disabled && !focusableWhenDisabled);
    let isAriaDisabled = $derived(disabled && focusableWhenDisabled);

    function handleClick(event: MouseEvent) {
        if (disabled) {
            event.preventDefault();
            return;
        }
        onclick?.(event);
    }
</script>

<button
    {type}
    class={buttonClasses}
    disabled={isDisabled}
    aria-disabled={isAriaDisabled || undefined}
    aria-label={ariaLabel}
    onclick={handleClick}
>
    {#if loading}
        <span class="{cls.spinner} {hasChildren ? cls.spinnerHasChildren : ''}">
            <LoadingSpinner />
        </span>
    {:else if icon}
        <span aria-hidden="true">
            {@render icon()}
        </span>
    {/if}
    {#if children}
        {@render children()}
    {/if}
</button>

// native-ports/shared-core/ui/vue/src/components/button/Button.vue
<script setup lang="ts">
import { computed, useSlots } from "vue";
import { button as cls } from "@lifesg/flagship-styles";
import { getButtonClasses } from "@lifesg/design-core";
import type {
    ButtonStyleType,
    ButtonSizeType,
    ButtonIconPosition,
} from "@lifesg/design-core";
import LoadingSpinner from "./LoadingSpinner.vue";

const props = withDefaults(
    defineProps<{
        styleType?: ButtonStyleType;
        sizeType?: ButtonSizeType;
        danger?: boolean;
        loading?: boolean;
        disabled?: boolean;
        focusableWhenDisabled?: boolean;
        iconPosition?: ButtonIconPosition;
    }>(),
    {
        styleType: "default",
        sizeType: "default",
        danger: false,
        loading: false,
        disabled: false,
        focusableWhenDisabled: false,
        iconPosition: "left",
    }
);

const slots = useSlots();

const iconOnly = computed(() => !!slots.icon && !slots.default);

const buttonClasses = computed(() =>
    getButtonClasses({
        styleType: props.styleType,
        sizeType: props.sizeType,
        danger: props.danger,
        disabled: props.disabled,
        focusableWhenDisabled: props.focusableWhenDisabled,
        iconOnly: iconOnly.value,
        iconPosition: props.iconPosition,
        hasChildren: !!slots.default,
    })
);

const isDisabledAttr = computed(
    () => props.disabled && !props.focusableWhenDisabled
);
</script>

<template>
    <button
        type="button"
        :class="buttonClasses"
        :disabled="isDisabledAttr || undefined"
        :aria-disabled="disabled || undefined"
    >
        <!-- Spinner or icon slot -->
        <template v-if="loading">
            <LoadingSpinner
                :class="[cls.spinner, !iconOnly && cls.spinnerHasChildren]"
            />
        </template>
        <template v-else-if="$slots.icon">
            <slot name="icon" />
        </template>

        <!-- Default slot (text content) -->
        <slot />
    </button>
</template>
