// src/native/svelte/button/Button.svelte
<script lang="ts">
    import type { Snippet } from "svelte";
    import { button as cls } from "../../styles";
    import LoadingSpinner from "./LoadingSpinner.svelte";
    import type { ButtonIconPosition, ButtonSizeType, ButtonStyleType } from "./types";

    interface Props {
        styleType?: ButtonStyleType;
        sizeType?: ButtonSizeType;
        danger?: boolean;
        loading?: boolean;
        disabled?: boolean;
        focusableWhenDisabled?: boolean;
        iconPosition?: ButtonIconPosition;
        type?: "button" | "submit" | "reset";
        "aria-label"?: string;
        onclick?: (event: MouseEvent) => void;
        icon?: Snippet;
        children?: Snippet;
    }

    let {
        styleType = "default",
        sizeType = "default",
        danger = false,
        loading = false,
        disabled = false,
        focusableWhenDisabled = false,
        iconPosition = "left",
        type = "button",
        "aria-label": ariaLabel,
        onclick,
        icon,
        children,
    }: Props = $props();

    let hasIcon = $derived(!!icon);
    let hasChildren = $derived(!!children);
    let isIconOnly = $derived(hasIcon && !hasChildren);

    let styleClass = $derived.by(() => {
        if (disabled && !focusableWhenDisabled) return cls.styleDisabled;
        switch (styleType) {
            case "secondary":
                return danger ? cls.styleSecondaryDanger : cls.styleSecondary;
            case "light":
                return danger ? cls.styleLightDanger : cls.styleLight;
            case "link":
                return danger ? cls.styleLinkDanger : cls.styleLink;
            default:
                return danger ? cls.styleDefaultDanger : cls.styleDefault;
        }
    });

    let sizeClass = $derived.by(() => {
        switch (sizeType) {
            case "small":
                return isIconOnly ? cls.sizeSmallIconOnly : cls.sizeSmall;
            case "large":
                return isIconOnly ? cls.sizeLargeIconOnly : cls.sizeLarge;
            default:
                return isIconOnly ? cls.sizeDefaultIconOnly : cls.sizeDefault;
        }
    });

    let buttonClasses = $derived.by(() => {
        const classes: string[] = [cls.root, styleClass, sizeClass];
        if (iconPosition === "right") classes.push(cls.iconRight);
        if (hasChildren) classes.push(cls.hasMinWidth);
        return classes.join(" ");
    });

    let isDisabled = $derived(disabled && !focusableWhenDisabled);
    let isAriaDisabled = $derived(disabled && focusableWhenDisabled);

    function handleClick(event: MouseEvent) {
        if (disabled) {
            event.preventDefault();
            return;
        }
        onclick?.(event);
    }
</script>

<button
    {type}
    class={buttonClasses}
    disabled={isDisabled}
    aria-disabled={isAriaDisabled || undefined}
    aria-label={ariaLabel}
    onclick={handleClick}
>
    {#if loading}
        <span class="{cls.spinner} {hasChildren ? cls.spinnerHasChildren : ''}">
            <LoadingSpinner />
        </span>
    {:else if icon}
        <span aria-hidden="true">
            {@render icon()}
        </span>
    {/if}
    {#if children}
        {@render children()}
    {/if}
</button>

// src/native/vue/button/Button.vue
<script setup lang="ts">
import { computed, useSlots } from "vue";
import { button as cls } from "../../styles";
import LoadingSpinner from "./LoadingSpinner.vue";
import type {
    ButtonStyleType,
    ButtonSizeType,
    ButtonIconPosition,
} from "./types";

const props = withDefaults(
    defineProps<{
        styleType?: ButtonStyleType;
        sizeType?: ButtonSizeType;
        danger?: boolean;
        loading?: boolean;
        disabled?: boolean;
        focusableWhenDisabled?: boolean;
        iconPosition?: ButtonIconPosition;
    }>(),
    {
        styleType: "default",
        sizeType: "default",
        danger: false,
        loading: false,
        disabled: false,
        focusableWhenDisabled: false,
        iconPosition: "left",
    }
);

const slots = useSlots();

const iconOnly = computed(() => !!slots.icon && !slots.default);

const styleClass = computed(() => {
    if (props.disabled) return cls.styleDisabled;

    const map: Record<string, Record<string, string>> = {
        default: { normal: cls.styleDefault, danger: cls.styleDefaultDanger },
        secondary: {
            normal: cls.styleSecondary,
            danger: cls.styleSecondaryDanger,
        },
        light: { normal: cls.styleLight, danger: cls.styleLightDanger },
        link: { normal: cls.styleLink, danger: cls.styleLinkDanger },
    };

    const variant = props.danger ? "danger" : "normal";
    return map[props.styleType]?.[variant] ?? cls.styleDefault;
});

const sizeClass = computed(() => {
    const map: Record<string, Record<string, string>> = {
        default: { normal: cls.sizeDefault, iconOnly: cls.sizeDefaultIconOnly },
        small: { normal: cls.sizeSmall, iconOnly: cls.sizeSmallIconOnly },
        large: { normal: cls.sizeLarge, iconOnly: cls.sizeLargeIconOnly },
    };

    const variant = iconOnly.value ? "iconOnly" : "normal";
    return map[props.sizeType]?.[variant] ?? cls.sizeDefault;
});

const buttonClasses = computed(() => {
    const classes: string[] = [cls.root];

    if (slots.icon && props.iconPosition === "right") {
        classes.push(cls.iconRight);
    }
    if (!iconOnly.value) {
        classes.push(cls.hasMinWidth);
    }

    classes.push(styleClass.value);
    classes.push(sizeClass.value);

    return classes;
});

const isDisabledAttr = computed(
    () => props.disabled && !props.focusableWhenDisabled
);
</script>

<template>
    <button
        type="button"
        :class="buttonClasses"
        :disabled="isDisabledAttr || undefined"
        :aria-disabled="disabled || undefined"
    >
        <!-- Spinner or icon slot -->
        <template v-if="loading">
            <LoadingSpinner
                :class="[cls.spinner, !iconOnly && cls.spinnerHasChildren]"
            />
        </template>
        <template v-else-if="$slots.icon">
            <slot name="icon" />
        </template>

        <!-- Default slot (text content) -->
        <slot />
    </button>
</template>
