// native-ports/shared-core/ui/lit/src/date-range-input/calendar.ts
import { LitElement, html } from "lit";
import { customElement, property } from "lit/decorators.js";
import dayjs, { type Dayjs } from "dayjs";
import { generateDays, isDisabledDay } from "@lifesg/design-core";
import { calendar } from "@lifesg/flagship-styles";
import { fdsComponentStyles } from "../shared-styles.js";
import "./day-cell.js";

const WEEKDAYS = ["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"];

@customElement("lifesg-calendar")
export class Calendar extends LitElement {
    static styles = [fdsComponentStyles];

    @property() calendarDate = "";
    @property() selectedStart = "";
    @property() selectedEnd = "";
    @property({ attribute: "min-date" }) minDate = "";
    @property({ attribute: "max-date" }) maxDate = "";
    @property({ type: Array, attribute: "disabled-dates" })
    disabledDates: string[] = [];

    render() {
        const date = this.calendarDate ? dayjs(this.calendarDate) : dayjs();
        const weeks = generateDays(date);

        return html`
            <div class=${calendar.root}>
                <div class=${calendar.grid}>
                    <div class=${calendar.weekdayHeader}>
                        ${WEEKDAYS.map((d) => html`<span>${d}</span>`)}
                    </div>
                    ${weeks.map(
                        (week) => html`
                            <div class=${calendar.weekRow}>
                                ${week.map((day) => this._renderDay(day, date))}
                            </div>
                        `
                    )}
                </div>
            </div>
        `;
    }

    private _renderDay(day: Dayjs, currentMonth: Dayjs) {
        const dateStr = day.format("YYYY-MM-DD");
        const isCurrentMonth = day.month() === currentMonth.month();
        const isToday = day.isSame(dayjs(), "day");
        const disabled = isDisabledDay(
            day,
            this.disabledDates,
            this.minDate || undefined,
            this.maxDate || undefined
        );

        const startDay = this.selectedStart ? dayjs(this.selectedStart) : null;
        const endDay = this.selectedEnd ? dayjs(this.selectedEnd) : null;

        const isSelectedStart = startDay ? day.isSame(startDay, "day") : false;
        const isSelectedEnd = endDay ? day.isSame(endDay, "day") : false;
        const isInRange =
            startDay && endDay
                ? day.isAfter(startDay, "day") && day.isBefore(endDay, "day")
                : false;

        return html`
            <lifesg-day-cell
                date=${dateStr}
                .day=${day.date()}
                ?current-month=${isCurrentMonth}
                ?today=${isToday}
                ?disabled=${disabled}
                ?selected-start=${isSelectedStart}
                ?selected-end=${isSelectedEnd}
                ?in-range=${isInRange || isSelectedStart || isSelectedEnd}
            ></lifesg-day-cell>
        `;
    }
}

declare global {
    interface HTMLElementTagNameMap {
        "lifesg-calendar": Calendar;
    }
}

// native-ports/shared-core/ui/react-native/src/date-range-input/Calendar.tsx
import React from "react";
import { View, Text } from "react-native";
import dayjs from "dayjs";
import { generateDays, isDisabledDay } from "@lifesg/design-core";
import { calendarStyles as s } from "./styles";
import { DayCell } from "./DayCell";

const WEEKDAYS = ["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"];

interface CalendarProps {
    calendarDate: string;
    selectedStart: string;
    selectedEnd: string;
    minDate?: string;
    maxDate?: string;
    disabledDates?: string[];
    onSelect: (date: string) => void;
}

export function Calendar({
    calendarDate,
    selectedStart,
    selectedEnd,
    minDate,
    maxDate,
    disabledDates,
    onSelect,
}: CalendarProps) {
    const date = calendarDate ? dayjs(calendarDate) : dayjs();
    const weeks = generateDays(date);
    const startDay = selectedStart ? dayjs(selectedStart) : null;
    const endDay = selectedEnd ? dayjs(selectedEnd) : null;

    return (
        <View style={s.container}>
            <View style={s.weekdayRow}>
                {WEEKDAYS.map((d) => (
                    <Text key={d} style={s.weekdayLabel}>
                        {d}
                    </Text>
                ))}
            </View>
            {weeks.map((week, wi) => (
                <View key={wi} style={s.weekRow}>
                    {week.map((day) => {
                        const dateStr = day.format("YYYY-MM-DD");
                        const isCurrentMonth = day.month() === date.month();
                        const isToday = day.isSame(dayjs(), "day");
                        const disabled = isDisabledDay(
                            day,
                            disabledDates,
                            minDate,
                            maxDate
                        );
                        const isSelectedStart = startDay
                            ? day.isSame(startDay, "day")
                            : false;
                        const isSelectedEnd = endDay
                            ? day.isSame(endDay, "day")
                            : false;
                        const isInRange =
                            startDay && endDay
                                ? (day.isAfter(startDay, "day") &&
                                      day.isBefore(endDay, "day")) ||
                                  isSelectedStart ||
                                  isSelectedEnd
                                : false;

                        return (
                            <DayCell
                                key={dateStr}
                                date={dateStr}
                                day={day.date()}
                                isCurrentMonth={isCurrentMonth}
                                isToday={isToday}
                                isDisabled={disabled}
                                isSelectedStart={isSelectedStart}
                                isSelectedEnd={isSelectedEnd}
                                isInRange={isInRange}
                                onSelect={onSelect}
                            />
                        );
                    })}
                </View>
            ))}
        </View>
    );
}
