// native-ports/vue/src/components/button/LoadingSpinner.vue
<script setup lang="ts">
import { loadingSpinner as cls } from "@lifesg/flagship-styles";
</script>

<template>
    <div :class="cls.root">
        <div :class="[cls.ring]"></div>
        <div :class="[cls.ring, cls.ring2]"></div>
        <div :class="[cls.ring, cls.ring3]"></div>
        <div :class="[cls.ring, cls.ring4]"></div>
    </div>
</template>

// native-ports/shared-core/ui/angular/src/app/components/button/loading-spinner.component.ts
import {
    Component,
    ViewEncapsulation,
    ChangeDetectionStrategy,
} from "@angular/core";
import { loadingSpinner } from "@lifesg/flagship-styles";

@Component({
    selector: "app-loading-spinner",
    standalone: true,
    template: `
        <div [class]="cls.root">
            <div [class]="cls.ring"></div>
            <div [class]="cls.ring + ' ' + cls.ring2"></div>
            <div [class]="cls.ring + ' ' + cls.ring3"></div>
            <div [class]="cls.ring + ' ' + cls.ring4"></div>
        </div>
    `,
    encapsulation: ViewEncapsulation.None,
    changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LoadingSpinnerComponent {
    readonly cls = loadingSpinner;
}
