// src/native/angular/date-range-input/date-range-input.component.ts
import {
    Component,
    input,
    output,
    signal,
    computed,
    effect,
    ElementRef,
    ViewEncapsulation,
    ChangeDetectionStrategy,
    OnInit,
    OnDestroy,
    inject,
} from "@angular/core";
import { StandaloneDateInputComponent } from "./standalone-date-input.component";
import { CalendarManagerComponent } from "./calendar-manager.component";
import { dayjs } from "./date-helpers";
import { dateRangeInput } from "../../styles";
import type { FocusType, CalendarAction, DateRangeValue } from "./types";

@Component({
    selector: "app-date-range-input",
    standalone: true,
    imports: [StandaloneDateInputComponent, CalendarManagerComponent],
    templateUrl: "./date-range-input.component.html",
    encapsulation: ViewEncapsulation.None,
    changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DateRangeInputComponent implements OnInit, OnDestroy {
    readonly value = input("");
    readonly valueEnd = input("");
    readonly minDate = input("");
    readonly maxDate = input("");
    readonly disabledDates = input<string[]>([]);
    readonly disabled = input(false);
    readonly error = input(false);
    readonly withButton = input(true);

    readonly dateChange = output<DateRangeValue>();

    private readonly elementRef = inject(ElementRef);

    readonly initialStart = signal("");
    readonly initialEnd = signal("");
    readonly selectedStart = signal("");
    readonly selectedEnd = signal("");
    readonly currentFocus = signal<FocusType>("none");
    readonly calendarOpen = signal(false);

    readonly cls = dateRangeInput;

    private boundDocumentClick = this.onDocumentClick.bind(this);

    readonly containerClasses = computed(() => {
        const classes = [this.cls.container];
        if (this.calendarOpen()) classes.push(this.cls.containerFocused);
        if (this.disabled()) classes.push(this.cls.containerDisabled);
        if (this.error()) classes.push(this.cls.containerError);
        return classes.join(" ");
    });

    readonly doneDisabled = computed(() => {
        const start = this.selectedStart();
        const end = this.selectedEnd();
        if (!start || !end) return true;
        return (
            !dayjs(start, "YYYY-MM-DD", true).isValid() ||
            !dayjs(end, "YYYY-MM-DD", true).isValid()
        );
    });

    readonly calendarDateForManager = computed(() => {
        return this.selectedStart() || dayjs().format("YYYY-MM-DD");
    });

    constructor() {
        effect(() => {
            const v = this.value();
            const ve = this.valueEnd();
            this.initialStart.set(v);
            this.selectedStart.set(v);
            this.initialEnd.set(ve);
            this.selectedEnd.set(ve);
        });
    }

    ngOnInit(): void {
        document.addEventListener("click", this.boundDocumentClick);
    }

    ngOnDestroy(): void {
        document.removeEventListener("click", this.boundDocumentClick);
    }

    handleContainerClick(): void {
        if (this.disabled()) return;
        if (!this.calendarOpen()) {
            this.handleFocus("start");
        }
    }

    handleFocus(focus: FocusType): void {
        this.currentFocus.set(focus);
        this.calendarOpen.set(true);
    }

    handleStartChange(event: { value: string }): void {
        this.selectedStart.set(event.value);
        if (!this.withButton() && event.value && this.selectedEnd()) {
            this.tryAutoConfirm();
        }
    }

    handleEndChange(event: { value: string }): void {
        this.selectedEnd.set(event.value);
        if (!this.withButton() && event.value && this.selectedStart()) {
            this.tryAutoConfirm();
        }
    }

    handleDaySelect(event: { date: string }): void {
        const date = event.date;
        const focus = this.currentFocus();

        if (focus === "start" || focus === "none") {
            this.selectedStart.set(date);
            this.currentFocus.set("end");
        } else {
            const start = dayjs(this.selectedStart());
            const end = dayjs(date);

            if (end.isBefore(start, "day")) {
                this.selectedStart.set(date);
                this.selectedEnd.set("");
                this.currentFocus.set("end");
            } else {
                this.selectedEnd.set(date);

                if (!this.withButton()) {
                    this.confirmSelection(this.selectedStart(), date);
                }
            }
        }
    }

    handleCalendarDismiss(action: CalendarAction): void {
        if (action === "confirmed") {
            this.confirmSelection(this.selectedStart(), this.selectedEnd());
        } else {
            this.selectedStart.set(this.initialStart());
            this.selectedEnd.set(this.initialEnd());
            this.currentFocus.set("none");
            this.calendarOpen.set(false);
        }
    }

    stopPropagation(event: Event): void {
        event.stopPropagation();
    }

    private confirmSelection(start: string, end: string): void {
        this.initialStart.set(start);
        this.initialEnd.set(end);
        this.selectedStart.set(start);
        this.selectedEnd.set(end);
        this.currentFocus.set("none");
        this.calendarOpen.set(false);

        this.dateChange.emit({ start, end });
    }

    private tryAutoConfirm(): void {
        const start = this.selectedStart();
        const end = this.selectedEnd();
        const s = dayjs(start, "YYYY-MM-DD", true);
        const e = dayjs(end, "YYYY-MM-DD", true);

        if (s.isValid() && e.isValid() && !e.isBefore(s, "day")) {
            this.confirmSelection(start, end);
        }
    }

    private onDocumentClick(event: MouseEvent): void {
        if (!this.calendarOpen()) return;
        const el = this.elementRef.nativeElement as HTMLElement;
        if (!el.contains(event.target as Node)) {
            this.selectedStart.set(this.initialStart());
            this.selectedEnd.set(this.initialEnd());
            this.currentFocus.set("none");
            this.calendarOpen.set(false);
        }
    }
}

<div [class]="cls.root">
    <div [class]="containerClasses()" (click)="handleContainerClick()">
        <app-standalone-date-input
            [value]="selectedStart()"
            label="Start date"
            [disabled]="disabled()"
            [focused]="currentFocus() === 'start'"
            (valueChange)="handleStartChange($event)"
            (inputFocus)="handleFocus('start')"
        />

        <span [class]="cls.separator">&ndash;</span>

        <app-standalone-date-input
            [value]="selectedEnd()"
            label="End date"
            [disabled]="disabled()"
            [focused]="currentFocus() === 'end'"
            (valueChange)="handleEndChange($event)"
            (inputFocus)="handleFocus('end')"
        />
    </div>

    @if (calendarOpen()) {
    <div [class]="cls.dropdown" (click)="stopPropagation($event)">
        <app-calendar-manager
            [calendarDate]="calendarDateForManager()"
            [selectedStart]="selectedStart()"
            [selectedEnd]="selectedEnd()"
            [minDate]="minDate()"
            [maxDate]="maxDate()"
            [disabledDates]="disabledDates()"
            [withButton]="withButton()"
            [doneDisabled]="doneDisabled()"
            (daySelect)="handleDaySelect($event)"
            (calendarDismiss)="handleCalendarDismiss($event)"
        />
    </div>
    }
</div>

// native-ports/react-native/src/date-range-input/DateRangeInput.tsx
import React, { useReducer } from "react";
import { View, Text, Pressable } from "react-native";
import { dayjs } from "./date-helpers";
import type {
    DateRangeInputProps,
    DateRangeInputState,
    FocusType,
    CalendarAction,
} from "./types";
import { dateRangeInputStyles as s } from "./styles";
import { StandaloneDateInput } from "./StandaloneDateInput";
import { CalendarManager } from "./CalendarManager";
import { CalendarBottomSheet } from "./CalendarBottomSheet";

type Action =
    | { type: "focus"; focus: FocusType }
    | { type: "blur" }
    | { type: "changeStart"; value: string }
    | { type: "changeEnd"; value: string }
    | { type: "cancel" }
    | { type: "done"; start: string; end: string }
    | { type: "resetRange"; start: string; end: string };

function reducer(
    state: DateRangeInputState,
    action: Action
): DateRangeInputState {
    switch (action.type) {
        case "focus":
            return {
                ...state,
                currentFocus: action.focus,
                calendarOpen: true,
            };
        case "blur":
            return {
                ...state,
                selectedStart: state.initialStart,
                selectedEnd: state.initialEnd,
                currentFocus: "none",
                calendarOpen: false,
            };
        case "changeStart":
            return { ...state, selectedStart: action.value };
        case "changeEnd":
            return { ...state, selectedEnd: action.value };
        case "cancel":
            return {
                ...state,
                selectedStart: state.initialStart,
                selectedEnd: state.initialEnd,
                currentFocus: "none",
                calendarOpen: false,
            };
        case "done":
            return {
                ...state,
                initialStart: action.start,
                initialEnd: action.end,
                selectedStart: action.start,
                selectedEnd: action.end,
                currentFocus: "none",
                calendarOpen: false,
            };
        case "resetRange":
            return {
                ...state,
                initialStart: action.start,
                selectedStart: action.start,
                initialEnd: action.end,
                selectedEnd: action.end,
            };
        default:
            return state;
    }
}

export function DateRangeInput({
    value = "",
    valueEnd = "",
    minDate,
    maxDate,
    disabledDates,
    disabled,
    error,
    withButton = true,
    onChange,
}: DateRangeInputProps) {
    const [state, dispatch] = useReducer(reducer, {
        initialStart: value,
        initialEnd: valueEnd,
        selectedStart: value,
        selectedEnd: valueEnd,
        currentFocus: "none",
        calendarOpen: false,
    });

    const handleFocus = (focus: FocusType) => {
        if (disabled) return;
        dispatch({ type: "focus", focus });
    };

    const handleStartChange = (val: string) => {
        dispatch({ type: "changeStart", value: val });
    };

    const handleEndChange = (val: string) => {
        dispatch({ type: "changeEnd", value: val });
    };

    const handleDaySelect = (date: string) => {
        if (state.currentFocus === "start" || state.currentFocus === "none") {
            dispatch({ type: "changeStart", value: date });
            dispatch({ type: "focus", focus: "end" });
        } else {
            const start = dayjs(state.selectedStart);
            const end = dayjs(date);

            if (end.isBefore(start, "day")) {
                dispatch({ type: "changeStart", value: date });
                dispatch({ type: "changeEnd", value: "" });
                dispatch({ type: "focus", focus: "end" });
            } else {
                dispatch({ type: "changeEnd", value: date });
                if (!withButton) {
                    confirmSelection(state.selectedStart, date);
                }
            }
        }
    };

    const handleDismiss = (action: CalendarAction) => {
        if (action === "confirmed") {
            confirmSelection(state.selectedStart, state.selectedEnd);
        } else {
            dispatch({ type: "cancel" });
        }
    };

    const confirmSelection = (start: string, end: string) => {
        dispatch({ type: "done", start, end });
        onChange?.(start, end);
    };

    const bothFilled =
        state.selectedStart &&
        state.selectedEnd &&
        dayjs(state.selectedStart, "YYYY-MM-DD", true).isValid() &&
        dayjs(state.selectedEnd, "YYYY-MM-DD", true).isValid();

    const containerStyle = [
        s.container,
        state.calendarOpen && s.containerFocused,
        disabled && s.containerDisabled,
        error && s.containerError,
    ];

    return (
        <View>
            <Pressable
                style={containerStyle}
                onPress={() => handleFocus("start")}
            >
                <StandaloneDateInput
                    value={state.selectedStart}
                    label="Start date"
                    disabled={disabled}
                    focused={state.currentFocus === "start"}
                    onChange={handleStartChange}
                    onFocus={() => handleFocus("start")}
                />
                <Text style={s.separator}>–</Text>
                <StandaloneDateInput
                    value={state.selectedEnd}
                    label="End date"
                    disabled={disabled}
                    focused={state.currentFocus === "end"}
                    onChange={handleEndChange}
                    onFocus={() => handleFocus("end")}
                />
            </Pressable>

            <CalendarBottomSheet
                visible={state.calendarOpen}
                onClose={() => dispatch({ type: "cancel" })}
            >
                <CalendarManager
                    calendarDate={
                        state.selectedStart || dayjs().format("YYYY-MM-DD")
                    }
                    selectedStart={state.selectedStart}
                    selectedEnd={state.selectedEnd}
                    minDate={minDate}
                    maxDate={maxDate}
                    disabledDates={disabledDates}
                    withButton={withButton}
                    doneDisabled={!bothFilled}
                    onSelect={handleDaySelect}
                    onDismiss={handleDismiss}
                />
            </CalendarBottomSheet>
        </View>
    );
}
