// native-ports/lit/src/date-range-input/calendar.ts
import { LitElement, html } from "lit";
import { customElement, property } from "lit/decorators.js";
import { dayjs, generateDays, isDisabledDay, Dayjs } from "./date-helpers.js";
import { calendar } from "@lifesg/flagship-styles";
import { fdsComponentStyles } from "../shared-styles.js";
import "./day-cell.js";

const WEEKDAYS = ["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"];

@customElement("lifesg-calendar")
export class Calendar extends LitElement {
    static styles = [fdsComponentStyles];

    @property() calendarDate = "";
    @property() selectedStart = "";
    @property() selectedEnd = "";
    @property({ attribute: "min-date" }) minDate = "";
    @property({ attribute: "max-date" }) maxDate = "";
    @property({ type: Array, attribute: "disabled-dates" })
    disabledDates: string[] = [];

    render() {
        const date = this.calendarDate ? dayjs(this.calendarDate) : dayjs();
        const weeks = generateDays(date);

        return html`
            <div class=${calendar.root}>
                <div class=${calendar.grid}>
                    <div class=${calendar.weekdayHeader}>
                        ${WEEKDAYS.map((d) => html`<span>${d}</span>`)}
                    </div>
                    ${weeks.map(
                        (week) => html`
                            <div class=${calendar.weekRow}>
                                ${week.map((day) => this._renderDay(day, date))}
                            </div>
                        `
                    )}
                </div>
            </div>
        `;
    }

    private _renderDay(day: Dayjs, currentMonth: Dayjs) {
        const dateStr = day.format("YYYY-MM-DD");
        const isCurrentMonth = day.month() === currentMonth.month();
        const isToday = day.isSame(dayjs(), "day");
        const disabled = isDisabledDay(
            day,
            this.disabledDates,
            this.minDate || undefined,
            this.maxDate || undefined
        );

        const startDay = this.selectedStart ? dayjs(this.selectedStart) : null;
        const endDay = this.selectedEnd ? dayjs(this.selectedEnd) : null;

        const isSelectedStart = startDay ? day.isSame(startDay, "day") : false;
        const isSelectedEnd = endDay ? day.isSame(endDay, "day") : false;
        const isInRange =
            startDay && endDay
                ? day.isAfter(startDay, "day") && day.isBefore(endDay, "day")
                : false;

        return html`
            <lifesg-day-cell
                date=${dateStr}
                .day=${day.date()}
                ?current-month=${isCurrentMonth}
                ?today=${isToday}
                ?disabled=${disabled}
                ?selected-start=${isSelectedStart}
                ?selected-end=${isSelectedEnd}
                ?in-range=${isInRange || isSelectedStart || isSelectedEnd}
            ></lifesg-day-cell>
        `;
    }
}

declare global {
    interface HTMLElementTagNameMap {
        "lifesg-calendar": Calendar;
    }
}

// native-ports/angular/src/app/components/date-range-input/calendar.component.ts
import {
    Component,
    input,
    output,
    computed,
    ViewEncapsulation,
    ChangeDetectionStrategy,
} from "@angular/core";
import { DayCellComponent } from "./day-cell.component";
import { dayjs, Dayjs, generateDays, isDisabledDay } from "./date-helpers";
import { calendar } from "@lifesg/flagship-styles";

const WEEKDAYS = ["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"];

@Component({
    selector: "app-calendar",
    standalone: true,
    imports: [DayCellComponent],
    templateUrl: "./calendar.component.html",
    encapsulation: ViewEncapsulation.None,
    changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CalendarComponent {
    readonly calendarDate = input("");
    readonly selectedStart = input("");
    readonly selectedEnd = input("");
    readonly minDate = input("");
    readonly maxDate = input("");
    readonly disabledDates = input<string[]>([]);

    readonly daySelect = output<{ date: string }>();

    readonly cls = calendar;
    readonly weekdays = WEEKDAYS;

    readonly weeks = computed(() => {
        const date = this.calendarDate() ? dayjs(this.calendarDate()) : dayjs();
        return generateDays(date);
    });

    readonly currentMonth = computed(() => {
        const date = this.calendarDate() ? dayjs(this.calendarDate()) : dayjs();
        return date.month();
    });

    isCurrentMonth(day: Dayjs): boolean {
        return day.month() === this.currentMonth();
    }

    isToday(day: Dayjs): boolean {
        return day.isSame(dayjs(), "day");
    }

    isDayDisabled(day: Dayjs): boolean {
        return isDisabledDay(
            day,
            this.disabledDates(),
            this.minDate() || undefined,
            this.maxDate() || undefined
        );
    }

    isSelectedStart(day: Dayjs): boolean {
        const start = this.selectedStart();
        return start ? day.isSame(dayjs(start), "day") : false;
    }

    isSelectedEnd(day: Dayjs): boolean {
        const end = this.selectedEnd();
        return end ? day.isSame(dayjs(end), "day") : false;
    }

    isInRange(day: Dayjs): boolean {
        const start = this.selectedStart();
        const end = this.selectedEnd();
        if (!start || !end) return false;
        const startDay = dayjs(start);
        const endDay = dayjs(end);
        const withinRange =
            day.isAfter(startDay, "day") && day.isBefore(endDay, "day");
        const isStart = day.isSame(startDay, "day");
        const isEnd = day.isSame(endDay, "day");
        return withinRange || isStart || isEnd;
    }

    getDayDateStr(day: Dayjs): string {
        return day.format("YYYY-MM-DD");
    }

    getDayNumber(day: Dayjs): number {
        return day.date();
    }

    trackWeek(index: number): number {
        return index;
    }

    trackDay(_index: number, day: Dayjs): string {
        return day.format("YYYY-MM-DD");
    }

    onDaySelect(event: { date: string }): void {
        this.daySelect.emit(event);
    }
}

<div [class]="cls.root">
    <div [class]="cls.grid">
        <div [class]="cls.weekdayHeader">
            @for (day of weekdays; track day) {
            <span>{{ day }}</span>
            }
        </div>
        @for (week of weeks(); track $index) {
        <div [class]="cls.weekRow">
            @for (day of week; track getDayDateStr(day)) {
            <app-day-cell
                [date]="getDayDateStr(day)"
                [day]="getDayNumber(day)"
                [currentMonth]="isCurrentMonth(day)"
                [today]="isToday(day)"
                [disabled]="isDayDisabled(day)"
                [selectedStart]="isSelectedStart(day)"
                [selectedEnd]="isSelectedEnd(day)"
                [inRange]="isInRange(day)"
                (daySelect)="onDaySelect($event)"
            />
            }
        </div>
        }
    </div>
</div>
