// native-ports/shared-core/ui/lit/src/date-range-input/calendar-manager.ts
import { LitElement, html, nothing } from "lit";
import { customElement, property, state } from "lit/decorators.js";
import dayjs, { type Dayjs } from "dayjs";
import {
    generateMonths,
    generateDecadeOfYears,
    isWithinRange,
} from "@lifesg/design-core";
import type { View, CalendarAction } from "./types.js";
import { calendarManager } from "@lifesg/flagship-styles";
import { fdsComponentStyles } from "../shared-styles.js";
import "./calendar.js";

@customElement("lifesg-calendar-manager")
export class CalendarManager extends LitElement {
    static styles = [fdsComponentStyles];

    @property() calendarDate = "";
    @property() selectedStart = "";
    @property() selectedEnd = "";
    @property({ attribute: "min-date" }) minDate = "";
    @property({ attribute: "max-date" }) maxDate = "";
    @property({ type: Array, attribute: "disabled-dates" })
    disabledDates: string[] = [];
    @property({ type: Boolean, attribute: "with-button" }) withButton = true;
    @property({ type: Boolean, attribute: "done-disabled" }) doneDisabled =
        false;

    @state() private _currentView: View = "default";
    @state() private _viewDate = "";

    connectedCallback() {
        super.connectedCallback();
        if (!this._viewDate) {
            this._viewDate = this.calendarDate || dayjs().format("YYYY-MM-DD");
        }
    }

    updated(changed: Map<string, unknown>) {
        if (changed.has("calendarDate") && this.calendarDate) {
            this._viewDate = this.calendarDate;
            this._currentView = "default";
        }
    }

    render() {
        const viewDate = this._viewDate ? dayjs(this._viewDate) : dayjs();

        return html`
            <div class=${calendarManager.root}>
                ${this._renderHeader(viewDate)}
                ${this._currentView === "default"
                    ? this._renderCalendar(viewDate)
                    : this._currentView === "month-options"
                    ? this._renderMonthPicker(viewDate)
                    : this._renderYearPicker(viewDate)}
                ${this.withButton ? this._renderFooter() : nothing}
            </div>
        `;
    }

    private _renderHeader(viewDate: Dayjs) {
        const minD = this.minDate ? dayjs(this.minDate) : undefined;
        const maxD = this.maxDate ? dayjs(this.maxDate) : undefined;

        let prevDisabled = false;
        let nextDisabled = false;

        if (this._currentView === "default") {
            if (minD)
                prevDisabled = !isWithinRange(
                    viewDate.subtract(1, "month"),
                    minD,
                    undefined,
                    "month"
                );
            if (maxD)
                nextDisabled = !isWithinRange(
                    viewDate.add(1, "month"),
                    undefined,
                    maxD,
                    "month"
                );
        } else if (this._currentView === "year-options") {
            const decade = Math.floor(viewDate.year() / 10) * 10;
            if (minD)
                prevDisabled = !isWithinRange(
                    viewDate.year(decade - 1),
                    minD,
                    undefined,
                    "year"
                );
            if (maxD)
                nextDisabled = !isWithinRange(
                    viewDate.year(decade + 10),
                    undefined,
                    maxD,
                    "year"
                );
        } else {
            if (minD)
                prevDisabled = !isWithinRange(
                    viewDate.subtract(1, "year"),
                    minD,
                    undefined,
                    "year"
                );
            if (maxD)
                nextDisabled = !isWithinRange(
                    viewDate.add(1, "year"),
                    undefined,
                    maxD,
                    "year"
                );
        }

        const monthLabel = viewDate.format("MMM");
        const yearLabel =
            this._currentView === "year-options"
                ? (() => {
                      const decade = Math.floor(viewDate.year() / 10) * 10;
                      return `${decade} - ${decade + 9}`;
                  })()
                : viewDate.format("YYYY");

        return html`
            <div class=${calendarManager.header}>
                <button
                    class=${calendarManager.navBtn}
                    ?disabled=${prevDisabled}
                    @click=${this._handlePrev}
                    aria-label="Previous"
                >
                    &#8249;
                </button>
                <div class=${calendarManager.headerLabels}>
                    <button
                        class="${calendarManager.headerLabel} ${this
                            ._currentView === "month-options"
                            ? calendarManager.headerLabelActive
                            : ""}"
                        @click=${this._toggleMonthView}
                    >
                        ${monthLabel}
                    </button>
                    <button
                        class="${calendarManager.headerLabel} ${this
                            ._currentView === "year-options"
                            ? calendarManager.headerLabelActive
                            : ""}"
                        @click=${this._toggleYearView}
                    >
                        ${yearLabel}
                    </button>
                </div>
                <button
                    class=${calendarManager.navBtn}
                    ?disabled=${nextDisabled}
                    @click=${this._handleNext}
                    aria-label="Next"
                >
                    &#8250;
                </button>
            </div>
        `;
    }

    private _renderCalendar(viewDate: Dayjs) {
        return html`
            <lifesg-calendar
                calendarDate=${viewDate.format("YYYY-MM-DD")}
                selectedStart=${this.selectedStart}
                selectedEnd=${this.selectedEnd}
                min-date=${this.minDate}
                max-date=${this.maxDate}
                .disabledDates=${this.disabledDates}
            ></lifesg-calendar>
        `;
    }

    private _renderMonthPicker(viewDate: Dayjs) {
        const months = generateMonths(viewDate);
        const minD = this.minDate ? dayjs(this.minDate) : undefined;
        const maxD = this.maxDate ? dayjs(this.maxDate) : undefined;

        return html`
            <div class=${calendarManager.monthGrid}>
                ${months.map((m) => {
                    const disabled = !isWithinRange(m, minD, maxD, "month");
                    const selected = m.month() === viewDate.month();
                    return html`
                        <button
                            class="${calendarManager.gridBtn} ${selected
                                ? calendarManager.gridBtnSelected
                                : ""}"
                            ?disabled=${disabled}
                            @click=${() => this._selectMonth(m)}
                        >
                            ${m.format("MMM")}
                        </button>
                    `;
                })}
            </div>
        `;
    }

    private _renderYearPicker(viewDate: Dayjs) {
        const years = generateDecadeOfYears(viewDate);
        const minD = this.minDate ? dayjs(this.minDate) : undefined;
        const maxD = this.maxDate ? dayjs(this.maxDate) : undefined;
        const decade = Math.floor(viewDate.year() / 10) * 10;

        return html`
            <div class=${calendarManager.yearGrid}>
                ${years.map((y) => {
                    const yr = y.year();
                    const disabled = !isWithinRange(y, minD, maxD, "year");
                    const outOfDecade = yr < decade || yr > decade + 9;
                    const selected = yr === viewDate.year();
                    return html`
                        <button
                            class="${calendarManager.gridBtn} ${selected
                                ? calendarManager.gridBtnSelected
                                : ""}"
                            ?disabled=${disabled}
                            style=${outOfDecade ? "opacity: 0.4" : ""}
                            @click=${() => this._selectYear(y)}
                        >
                            ${yr}
                        </button>
                    `;
                })}
            </div>
        `;
    }

    private _renderFooter() {
        return html`
            <div class=${calendarManager.footer}>
                <button
                    class=${calendarManager.footerBtn}
                    @click=${this._handleCancel}
                >
                    Cancel
                </button>
                <button
                    class="${calendarManager.footerBtn} ${calendarManager.footerBtnPrimary}"
                    ?disabled=${this.doneDisabled}
                    @click=${this._handleDone}
                >
                    Done
                </button>
            </div>
        `;
    }

    private _handlePrev() {
        const viewDate = dayjs(this._viewDate);
        if (this._currentView === "default") {
            this._viewDate = viewDate.subtract(1, "month").format("YYYY-MM-DD");
        } else if (this._currentView === "year-options") {
            this._viewDate = viewDate.subtract(10, "year").format("YYYY-MM-DD");
        } else {
            this._viewDate = viewDate.subtract(1, "year").format("YYYY-MM-DD");
        }
    }

    private _handleNext() {
        const viewDate = dayjs(this._viewDate);
        if (this._currentView === "default") {
            this._viewDate = viewDate.add(1, "month").format("YYYY-MM-DD");
        } else if (this._currentView === "year-options") {
            this._viewDate = viewDate.add(10, "year").format("YYYY-MM-DD");
        } else {
            this._viewDate = viewDate.add(1, "year").format("YYYY-MM-DD");
        }
    }

    private _toggleMonthView() {
        this._currentView =
            this._currentView === "month-options" ? "default" : "month-options";
    }

    private _toggleYearView() {
        this._currentView =
            this._currentView === "year-options" ? "default" : "year-options";
    }

    private _selectMonth(month: Dayjs) {
        const viewDate = dayjs(this._viewDate);
        this._viewDate = viewDate.month(month.month()).format("YYYY-MM-DD");
        this._currentView = "default";
    }

    private _selectYear(year: Dayjs) {
        const viewDate = dayjs(this._viewDate);
        this._viewDate = viewDate.year(year.year()).format("YYYY-MM-DD");
        this._currentView = "default";
    }

    private _handleCancel() {
        this.dispatchEvent(
            new CustomEvent<CalendarAction>("calendar-dismiss", {
                detail: "reset",
                bubbles: true,
                composed: true,
            })
        );
    }

    private _handleDone() {
        this.dispatchEvent(
            new CustomEvent<CalendarAction>("calendar-dismiss", {
                detail: "confirmed",
                bubbles: true,
                composed: true,
            })
        );
    }
}

declare global {
    interface HTMLElementTagNameMap {
        "lifesg-calendar-manager": CalendarManager;
    }
}

// native-ports/shared-core/ui/angular/src/app/components/date-range-input/calendar-manager.component.ts
import {
    Component,
    input,
    output,
    signal,
    computed,
    effect,
    ViewEncapsulation,
    ChangeDetectionStrategy,
    OnInit,
} from "@angular/core";
import { CalendarComponent } from "./calendar.component";
import dayjs, { Dayjs } from "dayjs";
import {
    generateMonths,
    generateDecadeOfYears,
    isWithinRange,
} from "@lifesg/design-core";
import { calendarManager } from "@lifesg/flagship-styles";
import type { View, CalendarAction } from "./types";

@Component({
    selector: "app-calendar-manager",
    standalone: true,
    imports: [CalendarComponent],
    templateUrl: "./calendar-manager.component.html",
    encapsulation: ViewEncapsulation.None,
    changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CalendarManagerComponent implements OnInit {
    readonly calendarDate = input("");
    readonly selectedStart = input("");
    readonly selectedEnd = input("");
    readonly minDate = input("");
    readonly maxDate = input("");
    readonly disabledDates = input<string[]>([]);
    readonly withButton = input(true);
    readonly doneDisabled = input(false);

    readonly daySelect = output<{ date: string }>();
    readonly calendarDismiss = output<CalendarAction>();

    readonly currentView = signal<View>("default");
    readonly viewDate = signal("");

    readonly cls = calendarManager;

    constructor() {
        effect(() => {
            const cd = this.calendarDate();
            if (cd) {
                this.viewDate.set(cd);
                this.currentView.set("default");
            }
        });
    }

    ngOnInit(): void {
        if (!this.viewDate()) {
            this.viewDate.set(
                this.calendarDate() || dayjs().format("YYYY-MM-DD")
            );
        }
    }

    readonly viewDateDayjs = computed(() => {
        const vd = this.viewDate();
        return vd ? dayjs(vd) : dayjs();
    });

    readonly monthLabel = computed(() => {
        return this.viewDateDayjs().format("MMM");
    });

    readonly yearLabel = computed(() => {
        if (this.currentView() === "year-options") {
            const decade = Math.floor(this.viewDateDayjs().year() / 10) * 10;
            return `${decade} - ${decade + 9}`;
        }
        return this.viewDateDayjs().format("YYYY");
    });

    readonly prevDisabled = computed(() => {
        const viewDate = this.viewDateDayjs();
        const minD = this.minDate() ? dayjs(this.minDate()) : undefined;
        if (!minD) return false;

        if (this.currentView() === "default") {
            return !isWithinRange(
                viewDate.subtract(1, "month"),
                minD,
                undefined,
                "month"
            );
        } else if (this.currentView() === "year-options") {
            const decade = Math.floor(viewDate.year() / 10) * 10;
            return !isWithinRange(
                viewDate.year(decade - 1),
                minD,
                undefined,
                "year"
            );
        } else {
            return !isWithinRange(
                viewDate.subtract(1, "year"),
                minD,
                undefined,
                "year"
            );
        }
    });

    readonly nextDisabled = computed(() => {
        const viewDate = this.viewDateDayjs();
        const maxD = this.maxDate() ? dayjs(this.maxDate()) : undefined;
        if (!maxD) return false;

        if (this.currentView() === "default") {
            return !isWithinRange(
                viewDate.add(1, "month"),
                undefined,
                maxD,
                "month"
            );
        } else if (this.currentView() === "year-options") {
            const decade = Math.floor(viewDate.year() / 10) * 10;
            return !isWithinRange(
                viewDate.year(decade + 10),
                undefined,
                maxD,
                "year"
            );
        } else {
            return !isWithinRange(
                viewDate.add(1, "year"),
                undefined,
                maxD,
                "year"
            );
        }
    });

    readonly months = computed(() => {
        return generateMonths(this.viewDateDayjs());
    });

    readonly years = computed(() => {
        return generateDecadeOfYears(this.viewDateDayjs());
    });

    readonly currentDecade = computed(() => {
        return Math.floor(this.viewDateDayjs().year() / 10) * 10;
    });

    readonly monthHeaderClass = computed(() => {
        return this.currentView() === "month-options"
            ? this.cls.headerLabel + " " + this.cls.headerLabelActive
            : this.cls.headerLabel;
    });

    readonly yearHeaderClass = computed(() => {
        return this.currentView() === "year-options"
            ? this.cls.headerLabel + " " + this.cls.headerLabelActive
            : this.cls.headerLabel;
    });

    isMonthDisabled(month: Dayjs): boolean {
        const minD = this.minDate() ? dayjs(this.minDate()) : undefined;
        const maxD = this.maxDate() ? dayjs(this.maxDate()) : undefined;
        return !isWithinRange(month, minD, maxD, "month");
    }

    isMonthSelected(month: Dayjs): boolean {
        return month.month() === this.viewDateDayjs().month();
    }

    isYearDisabled(year: Dayjs): boolean {
        const minD = this.minDate() ? dayjs(this.minDate()) : undefined;
        const maxD = this.maxDate() ? dayjs(this.maxDate()) : undefined;
        return !isWithinRange(year, minD, maxD, "year");
    }

    isYearSelected(year: Dayjs): boolean {
        return year.year() === this.viewDateDayjs().year();
    }

    isYearOutOfDecade(year: Dayjs): boolean {
        const yr = year.year();
        const decade = this.currentDecade();
        return yr < decade || yr > decade + 9;
    }

    getMonthLabel(month: Dayjs): string {
        return month.format("MMM");
    }

    getYearNumber(year: Dayjs): number {
        return year.year();
    }

    getGridBtnClass(selected: boolean): string {
        return selected
            ? this.cls.gridBtn + " " + this.cls.gridBtnSelected
            : this.cls.gridBtn;
    }

    handlePrev(): void {
        const viewDate = this.viewDateDayjs();
        if (this.currentView() === "default") {
            this.viewDate.set(
                viewDate.subtract(1, "month").format("YYYY-MM-DD")
            );
        } else if (this.currentView() === "year-options") {
            this.viewDate.set(
                viewDate.subtract(10, "year").format("YYYY-MM-DD")
            );
        } else {
            this.viewDate.set(
                viewDate.subtract(1, "year").format("YYYY-MM-DD")
            );
        }
    }

    handleNext(): void {
        const viewDate = this.viewDateDayjs();
        if (this.currentView() === "default") {
            this.viewDate.set(viewDate.add(1, "month").format("YYYY-MM-DD"));
        } else if (this.currentView() === "year-options") {
            this.viewDate.set(viewDate.add(10, "year").format("YYYY-MM-DD"));
        } else {
            this.viewDate.set(viewDate.add(1, "year").format("YYYY-MM-DD"));
        }
    }

    toggleMonthView(): void {
        this.currentView.set(
            this.currentView() === "month-options" ? "default" : "month-options"
        );
    }

    toggleYearView(): void {
        this.currentView.set(
            this.currentView() === "year-options" ? "default" : "year-options"
        );
    }

    selectMonth(month: Dayjs): void {
        const viewDate = this.viewDateDayjs();
        this.viewDate.set(viewDate.month(month.month()).format("YYYY-MM-DD"));
        this.currentView.set("default");
    }

    selectYear(year: Dayjs): void {
        const viewDate = this.viewDateDayjs();
        this.viewDate.set(viewDate.year(year.year()).format("YYYY-MM-DD"));
        this.currentView.set("default");
    }

    handleCancel(): void {
        this.calendarDismiss.emit("reset");
    }

    handleDone(): void {
        this.calendarDismiss.emit("confirmed");
    }

    onDaySelect(event: { date: string }): void {
        this.daySelect.emit(event);
    }

    trackMonth(index: number): number {
        return index;
    }

    trackYear(index: number): number {
        return index;
    }
}

<div [class]="cls.root">
    <!-- Header -->
    <div [class]="cls.header">
        <button
            [class]="cls.navBtn"
            [disabled]="prevDisabled()"
            (click)="handlePrev()"
            aria-label="Previous"
        >
            &#8249;
        </button>
        <div [class]="cls.headerLabels">
            <button [class]="monthHeaderClass()" (click)="toggleMonthView()">
                {{ monthLabel() }}
            </button>
            <button [class]="yearHeaderClass()" (click)="toggleYearView()">
                {{ yearLabel() }}
            </button>
        </div>
        <button
            [class]="cls.navBtn"
            [disabled]="nextDisabled()"
            (click)="handleNext()"
            aria-label="Next"
        >
            &#8250;
        </button>
    </div>

    <!-- Content -->
    @if (currentView() === 'default') {
    <app-calendar
        [calendarDate]="viewDate()"
        [selectedStart]="selectedStart()"
        [selectedEnd]="selectedEnd()"
        [minDate]="minDate()"
        [maxDate]="maxDate()"
        [disabledDates]="disabledDates()"
        (daySelect)="onDaySelect($event)"
    />
    } @else if (currentView() === 'month-options') {
    <div [class]="cls.monthGrid">
        @for (month of months(); track $index) {
        <button
            [class]="getGridBtnClass(isMonthSelected(month))"
            [disabled]="isMonthDisabled(month)"
            (click)="selectMonth(month)"
        >
            {{ getMonthLabel(month) }}
        </button>
        }
    </div>
    } @else {
    <div [class]="cls.yearGrid">
        @for (year of years(); track $index) {
        <button
            [class]="getGridBtnClass(isYearSelected(year))"
            [disabled]="isYearDisabled(year)"
            [style.opacity]="isYearOutOfDecade(year) ? '0.4' : '1'"
            (click)="selectYear(year)"
        >
            {{ getYearNumber(year) }}
        </button>
        }
    </div>
    }

    <!-- Footer -->
    @if (withButton()) {
    <div [class]="cls.footer">
        <button [class]="cls.footerBtn" (click)="handleCancel()">Cancel</button>
        <button
            [class]="cls.footerBtn + ' ' + cls.footerBtnPrimary"
            [disabled]="doneDisabled()"
            (click)="handleDone()"
        >
            Done
        </button>
    </div>
    }
</div>
