// native-ports/svelte/src/date-range-input/DateRangeInput.svelte
<script lang="ts">
    import type { Dayjs } from "dayjs";
    import dayjs from "dayjs";
    import { dateRangeInput as cls } from "@lifesg/flagship-styles";
    import CalendarManager from "./CalendarManager.svelte";
    import StandaloneDateInput from "./StandaloneDateInput.svelte";
    import { sanitizeInput, toDayjs } from "./date-helpers";
    import type { CalendarAction, DateRangeValue, FocusType } from "./types";
    import { onMount, tick } from "svelte";

    interface Props {
        startDate?: string;
        endDate?: string;
        minDate?: string;
        maxDate?: string;
        disabledDates?: string[];
        disabled?: boolean;
        error?: boolean;
        label?: string;
        onchange?: (value: DateRangeValue) => void;
    }

    let {
        startDate = "",
        endDate = "",
        minDate,
        maxDate,
        disabledDates,
        disabled = false,
        error = false,
        label,
        onchange,
    }: Props = $props();

    let initialStart = $state("");
    let initialEnd = $state("");
    let selectedStart = $state("");
    let selectedEnd = $state("");
    let currentFocus = $state<FocusType>("none");
    let calendarOpen = $state(false);
    let focused = $state(false);
    let hoverDate = $state("");

    let wrapperEl: HTMLDivElement | undefined = $state();
    let startInputRef: StandaloneDateInput | undefined = $state();
    let endInputRef: StandaloneDateInput | undefined = $state();
    let calendarManagerRef: CalendarManager | undefined = $state();

    $effect(() => {
        initialStart = startDate || "";
        initialEnd = endDate || "";
        selectedStart = startDate || "";
        selectedEnd = endDate || "";
    });

    let calendarInitialDate = $derived.by(() => {
        if (selectedStart) return selectedStart;
        if (selectedEnd) return selectedEnd;
        return undefined;
    });

    let doneButtonDisabled = $derived.by(() => {
        if (!selectedStart || !selectedEnd) return true;
        if (dayjs(selectedStart).isAfter(selectedEnd, "day")) return true;
        return false;
    });

    let isStartFocused = $derived(currentFocus === "start");
    let isEndFocused = $derived(currentFocus === "end");

    let containerClasses = $derived.by(() => {
        const classes: string[] = [cls.container];
        if (focused) classes.push(cls.containerFocused);
        if (disabled) classes.push(cls.containerDisabled);
        if (error) classes.push(cls.containerError);
        return classes.join(" ");
    });

    function handleOutsideClick(event: MouseEvent) {
        if (!wrapperEl) return;
        if (wrapperEl.contains(event.target as Node)) return;
        if (calendarOpen) {
            handleCancel();
        }
    }

    onMount(() => {
        document.addEventListener("mousedown", handleOutsideClick);
        return () => {
            document.removeEventListener("mousedown", handleOutsideClick);
        };
    });

    function handleStartFocus() {
        if (disabled) return;
        currentFocus = "start";
        focused = true;
        calendarOpen = true;
    }

    function handleEndFocus() {
        if (disabled) return;
        currentFocus = "end";
        focused = true;
        calendarOpen = true;
    }

    function handleStartChange(value: string) {
        selectedStart = value;
        if (value && sanitizeInput(value)) {
            calendarManagerRef?.setCalendarDateTo(value);
        }
    }

    function handleEndChange(value: string) {
        selectedEnd = value;
        if (value && sanitizeInput(value)) {
            calendarManagerRef?.setCalendarDateTo(value);
        }
    }

    function handleStartBlur(valid: boolean) {
        if (!calendarOpen) {
            focused = false;
            currentFocus = "none";
        }
    }

    function handleEndBlur(valid: boolean) {
        if (!calendarOpen) {
            focused = false;
            currentFocus = "none";
        }
    }

    function handleDaySelect(date: Dayjs) {
        const dateStr = date.format("YYYY-MM-DD");

        if (currentFocus === "start") {
            selectedStart = dateStr;
            if (selectedEnd && date.isAfter(selectedEnd, "day")) {
                selectedEnd = "";
            }
            currentFocus = "end";
            tick().then(() => endInputRef?.focusDay());
        } else if (currentFocus === "end") {
            if (selectedStart && date.isBefore(selectedStart, "day")) {
                selectedStart = dateStr;
            } else {
                selectedEnd = dateStr;
            }
        } else {
            selectedStart = dateStr;
            currentFocus = "end";
            tick().then(() => endInputRef?.focusDay());
        }

        hoverDate = "";
    }

    function handleDayHover(dateStr: string) {
        hoverDate = dateStr;
    }

    function handleDismiss(action: CalendarAction) {
        if (action === "confirmed") {
            handleDone();
        } else {
            handleCancel();
        }
    }

    function handleDone() {
        initialStart = selectedStart;
        initialEnd = selectedEnd;
        calendarOpen = false;
        focused = false;
        currentFocus = "none";
        hoverDate = "";

        onchange?.({ start: selectedStart, end: selectedEnd });
    }

    function handleCancel() {
        selectedStart = initialStart;
        selectedEnd = initialEnd;
        calendarOpen = false;
        focused = false;
        currentFocus = "none";
        hoverDate = "";

        startInputRef?.resetInput();
        endInputRef?.resetInput();
    }

    function handleCalendarDateChange(date: Dayjs) {
        // no-op for now
    }

    function handleInputWrapperClick() {
        if (disabled) return;
        if (!calendarOpen) {
            calendarOpen = true;
            focused = true;
            if (currentFocus === "none") {
                currentFocus = "start";
                tick().then(() => startInputRef?.focusDay());
            }
        }
    }
</script>

<div bind:this={wrapperEl} class={cls.root} style="position: relative; max-width: 400px;">
    {#if label}
        <label
            style="display: block; font-size: 14px; font-weight: 600; color: var(--fds-colour-text); margin-bottom: 8px;"
        >
            {label}
        </label>
    {/if}

    <!-- svelte-ignore a11y_click_events_have_key_events -->
    <!-- svelte-ignore a11y_no_static_element_interactions -->
    <div class={containerClasses} onclick={handleInputWrapperClick}>
        <StandaloneDateInput
            bind:this={startInputRef}
            side="start"
            value={selectedStart}
            focused={isStartFocused}
            {disabled}
            label="Start date"
            onchange={handleStartChange}
            onfocus={handleStartFocus}
            onblur={handleStartBlur}
        />
        <span class={cls.separator}>to</span>
        <StandaloneDateInput
            bind:this={endInputRef}
            side="end"
            value={selectedEnd}
            focused={isEndFocused}
            {disabled}
            label="End date"
            onchange={handleEndChange}
            onfocus={handleEndFocus}
            onblur={handleEndBlur}
        />
    </div>

    {#if calendarOpen && !disabled}
        <div class={cls.dropdown}>
            <CalendarManager
                bind:this={calendarManagerRef}
                initialCalendarDate={calendarInitialDate}
                startDate={selectedStart}
                endDate={selectedEnd}
                {currentFocus}
                {hoverDate}
                {minDate}
                {maxDate}
                {disabledDates}
                withButton={true}
                {doneButtonDisabled}
                ondismiss={handleDismiss}
                onselectday={handleDaySelect}
                onhoverday={handleDayHover}
                oncalendardatechange={handleCalendarDateChange}
            />
        </div>
    {/if}
</div>

// native-ports/vue/src/components/date-range-input/DateRangeInput.vue
<script setup lang="ts">
import type { Dayjs } from "dayjs";
import dayjs from "dayjs";
import {
    computed,
    nextTick,
    onBeforeUnmount,
    onMounted,
    reactive,
    ref,
    watch,
} from "vue";
import { dateRangeInput as cls } from "@lifesg/flagship-styles";
import CalendarManager from "./CalendarManager.vue";
import { sanitizeInput, toDayjs } from "./date-helpers";
import StandaloneDateInput from "./StandaloneDateInput.vue";
import type {
    CalendarAction,
    DateRangeState,
    DateRangeValue,
    FocusType,
} from "./types";

const props = withDefaults(
    defineProps<{
        startDate?: string;
        endDate?: string;
        minDate?: string;
        maxDate?: string;
        disabledDates?: string[];
        disabled?: boolean;
        error?: boolean;
        label?: string;
    }>(),
    {
        startDate: "",
        endDate: "",
        disabled: false,
        error: false,
    }
);

const emit = defineEmits<{
    change: [value: DateRangeValue];
}>();

// ---- state ----
const state = reactive<DateRangeState>({
    initialStart: props.startDate || "",
    initialEnd: props.endDate || "",
    selectedStart: props.startDate || "",
    selectedEnd: props.endDate || "",
    currentFocus: "none",
    calendarOpen: false,
    focused: false,
});

const hoverDate = ref("");

// ---- refs ----
const wrapperRef = ref<HTMLDivElement | null>(null);
const startInputRef = ref<InstanceType<typeof StandaloneDateInput> | null>(
    null
);
const endInputRef = ref<InstanceType<typeof StandaloneDateInput> | null>(null);
const calendarManagerRef = ref<InstanceType<typeof CalendarManager> | null>(
    null
);

// ---- sync props to state ----
watch(
    () => [props.startDate, props.endDate],
    ([s, e]) => {
        state.initialStart = s || "";
        state.initialEnd = e || "";
        state.selectedStart = s || "";
        state.selectedEnd = e || "";
    }
);

// ---- computed ----
const calendarInitialDate = computed(() => {
    if (state.selectedStart) return state.selectedStart;
    if (state.selectedEnd) return state.selectedEnd;
    return undefined;
});

const doneButtonDisabled = computed(() => {
    // Disabled if we don't have both start and end
    if (!state.selectedStart || !state.selectedEnd) return true;
    // Disabled if start > end
    if (dayjs(state.selectedStart).isAfter(state.selectedEnd, "day"))
        return true;
    return false;
});

const isStartFocused = computed(() => state.currentFocus === "start");
const isEndFocused = computed(() => state.currentFocus === "end");

const containerClasses = computed(() => {
    const classes: string[] = [cls.container];
    if (state.focused) classes.push(cls.containerFocused);
    if (props.disabled) classes.push(cls.containerDisabled);
    if (props.error) classes.push(cls.containerError);
    return classes;
});

// ---- outside click ----
function handleOutsideClick(event: MouseEvent) {
    if (!wrapperRef.value) return;
    if (wrapperRef.value.contains(event.target as Node)) return;

    if (state.calendarOpen) {
        handleCancel();
    }
}

onMounted(() => {
    document.addEventListener("mousedown", handleOutsideClick);
});

onBeforeUnmount(() => {
    document.removeEventListener("mousedown", handleOutsideClick);
});

// ---- input handlers ----
function handleStartFocus() {
    if (props.disabled) return;
    state.currentFocus = "start";
    state.focused = true;
    state.calendarOpen = true;
}

function handleEndFocus() {
    if (props.disabled) return;
    state.currentFocus = "end";
    state.focused = true;
    state.calendarOpen = true;
}

function handleStartChange(value: string) {
    state.selectedStart = value;

    // If valid, navigate calendar to that month
    if (value && sanitizeInput(value)) {
        calendarManagerRef.value?.setCalendarDateTo(value);
    }
}

function handleEndChange(value: string) {
    state.selectedEnd = value;

    if (value && sanitizeInput(value)) {
        calendarManagerRef.value?.setCalendarDateTo(value);
    }
}

function handleStartBlur(valid: boolean) {
    // If calendar is not open, the whole component lost focus
    if (!state.calendarOpen) {
        state.focused = false;
        state.currentFocus = "none";
    }
}

function handleEndBlur(valid: boolean) {
    if (!state.calendarOpen) {
        state.focused = false;
        state.currentFocus = "none";
    }
}

// ---- calendar handlers ----
function handleDaySelect(date: Dayjs) {
    const dateStr = date.format("YYYY-MM-DD");

    if (state.currentFocus === "start") {
        state.selectedStart = dateStr;

        // If the new start is after the current end, clear end
        if (state.selectedEnd && date.isAfter(state.selectedEnd, "day")) {
            state.selectedEnd = "";
        }

        // Auto-move focus to end
        state.currentFocus = "end";
        nextTick(() => {
            endInputRef.value?.focusDay();
        });
    } else if (state.currentFocus === "end") {
        // If selected date is before start, it becomes the new start instead
        if (state.selectedStart && date.isBefore(state.selectedStart, "day")) {
            state.selectedStart = dateStr;
            // Keep focus on end so user can pick the end date
        } else {
            state.selectedEnd = dateStr;
        }
    } else {
        // No focus yet - treat as start
        state.selectedStart = dateStr;
        state.currentFocus = "end";
        nextTick(() => {
            endInputRef.value?.focusDay();
        });
    }

    hoverDate.value = "";
}

function handleDayHover(dateStr: string) {
    hoverDate.value = dateStr;
}

function handleDismiss(action: CalendarAction) {
    if (action === "confirmed") {
        handleDone();
    } else {
        handleCancel();
    }
}

function handleDone() {
    // Confirm selection
    state.initialStart = state.selectedStart;
    state.initialEnd = state.selectedEnd;
    state.calendarOpen = false;
    state.focused = false;
    state.currentFocus = "none";
    hoverDate.value = "";

    emit("change", {
        start: state.selectedStart,
        end: state.selectedEnd,
    });
}

function handleCancel() {
    // Revert to initial values
    state.selectedStart = state.initialStart;
    state.selectedEnd = state.initialEnd;
    state.calendarOpen = false;
    state.focused = false;
    state.currentFocus = "none";
    hoverDate.value = "";

    // Reset inputs
    startInputRef.value?.resetInput();
    endInputRef.value?.resetInput();
}

function handleCalendarDateChange(date: Dayjs) {
    // Could be used for external tracking; no-op for now
}

function handleInputWrapperClick() {
    if (props.disabled) return;
    if (!state.calendarOpen) {
        state.calendarOpen = true;
        state.focused = true;
        if (state.currentFocus === "none") {
            state.currentFocus = "start";
            nextTick(() => {
                startInputRef.value?.focusDay();
            });
        }
    }
}
</script>

<template>
    <div
        ref="wrapperRef"
        :class="cls.root"
        style="position: relative; max-width: 400px"
    >
        <!-- Label -->
        <label
            v-if="label"
            style="
                display: block;
                font-size: 14px;
                font-weight: 600;
                color: var(--fds-colour-text);
                margin-bottom: 8px;
            "
        >
            {{ label }}
        </label>

        <!-- Input row -->
        <div :class="containerClasses" @click="handleInputWrapperClick">
            <StandaloneDateInput
                ref="startInputRef"
                side="start"
                :value="state.selectedStart"
                :focused="isStartFocused"
                :disabled="disabled"
                label="Start date"
                @change="handleStartChange"
                @focus="handleStartFocus"
                @blur="handleStartBlur"
            />
            <span :class="cls.separator">to</span>
            <StandaloneDateInput
                ref="endInputRef"
                side="end"
                :value="state.selectedEnd"
                :focused="isEndFocused"
                :disabled="disabled"
                label="End date"
                @change="handleEndChange"
                @focus="handleEndFocus"
                @blur="handleEndBlur"
            />
        </div>

        <!-- Calendar dropdown -->
        <div v-if="state.calendarOpen && !disabled" :class="cls.dropdown">
            <CalendarManager
                ref="calendarManagerRef"
                :initial-calendar-date="calendarInitialDate"
                :start-date="state.selectedStart"
                :end-date="state.selectedEnd"
                :current-focus="state.currentFocus"
                :hover-date="hoverDate"
                :min-date="minDate"
                :max-date="maxDate"
                :disabled-dates="disabledDates"
                :with-button="true"
                :done-button-disabled="doneButtonDisabled"
                @dismiss="handleDismiss"
                @select-day="handleDaySelect"
                @hover-day="handleDayHover"
                @calendar-date-change="handleCalendarDateChange"
            />
        </div>
    </div>
</template>
