// native-ports/shared-core/ui/svelte/demo/App.svelte
<script lang="ts">
    import DateRangeInput from "@lib/date-range-input/DateRangeInput.svelte";
    import Button from "@lib/button/Button.svelte";
    import type { DateRangeValue } from "@lib/date-range-input/types";

    function handleChange(value: DateRangeValue) {
        console.log("DateRange changed:", value);
    }
</script>

<main>
    <h1>Svelte 5 — Flagship Components</h1>

    <section>
        <h2>DateRangeInput</h2>

        <h3>Default</h3>
        <DateRangeInput label="Select dates" onchange={handleChange} />

        <h3>With initial values</h3>
        <DateRangeInput
            label="Pre-filled"
            startDate="2025-01-15"
            endDate="2025-01-25"
            onchange={handleChange}
        />

        <h3>Disabled</h3>
        <DateRangeInput
            label="Disabled"
            startDate="2025-03-01"
            endDate="2025-03-10"
            disabled
        />

        <h3>Error</h3>
        <DateRangeInput label="With error" error />
    </section>

    <section>
        <h2>Button</h2>

        <h3>Style Types</h3>
        <div class="button-row">
            <Button>Default</Button>
            <Button styleType="secondary">Secondary</Button>
            <Button styleType="light">Light</Button>
            <Button styleType="link">Link</Button>
        </div>

        <h3>Danger Variants</h3>
        <div class="button-row">
            <Button danger>Default Danger</Button>
            <Button styleType="secondary" danger>Secondary Danger</Button>
            <Button styleType="light" danger>Light Danger</Button>
            <Button styleType="link" danger>Link Danger</Button>
        </div>

        <h3>Sizes</h3>
        <div class="button-row">
            <Button sizeType="large">Large</Button>
            <Button sizeType="default">Default</Button>
            <Button sizeType="small">Small</Button>
        </div>

        <h3>Disabled</h3>
        <div class="button-row">
            <Button disabled>Disabled</Button>
            <Button styleType="secondary" disabled>Disabled Secondary</Button>
        </div>

        <h3>Loading</h3>
        <div class="button-row">
            <Button loading>Loading</Button>
            <Button styleType="secondary" loading>Loading Secondary</Button>
        </div>

        <h3>Icon + Text</h3>
        <div class="button-row">
            <Button>
                {#snippet icon()}
                    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor">
                        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5" />
                    </svg>
                {/snippet}
                Icon Left
            </Button>
            <Button iconPosition="right">
                {#snippet icon()}
                    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor">
                        <path d="M5 12h14M12 5l7 7-7 7" />
                    </svg>
                {/snippet}
                Icon Right
            </Button>
        </div>

        <h3>Icon Only</h3>
        <div class="button-row">
            <Button aria-label="Settings" sizeType="large">
                {#snippet icon()}
                    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor">
                        <path d="M12 15.5A3.5 3.5 0 0 1 8.5 12 3.5 3.5 0 0 1 12 8.5a3.5 3.5 0 0 1 3.5 3.5 3.5 3.5 0 0 1-3.5 3.5m7.43-2.53a7.76 7.76 0 0 0 .07-1 7.76 7.76 0 0 0-.07-.97l2.11-1.63a.5.5 0 0 0 .12-.64l-2-3.46a.5.5 0 0 0-.61-.22l-2.49 1a7.15 7.15 0 0 0-1.69-.98l-.38-2.65A.49.49 0 0 0 14 2h-4a.49.49 0 0 0-.49.42l-.38 2.65a7.15 7.15 0 0 0-1.69.98l-2.49-1a.5.5 0 0 0-.61.22l-2 3.46a.49.49 0 0 0 .12.64L4.57 11a7.9 7.9 0 0 0 0 1.97l-2.11 1.66a.5.5 0 0 0-.12.64l2 3.46a.5.5 0 0 0 .61.22l2.49-1a7.15 7.15 0 0 0 1.69.98l.38 2.65c.05.24.26.42.49.42h4c.24 0 .44-.18.49-.42l.38-2.65a7.15 7.15 0 0 0 1.69-.98l2.49 1a.5.5 0 0 0 .61-.22l2-3.46a.49.49 0 0 0-.12-.64l-2.11-1.66z" />
                    </svg>
                {/snippet}
            </Button>
            <Button aria-label="Close">
                {#snippet icon()}
                    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor">
                        <path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z" />
                    </svg>
                {/snippet}
            </Button>
            <Button aria-label="Close" sizeType="small">
                {#snippet icon()}
                    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor">
                        <path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z" />
                    </svg>
                {/snippet}
            </Button>
        </div>
    </section>
</main>

<style>
    :global(body) {
        font-family: system-ui, -apple-system, sans-serif;
        margin: 0;
        padding: 24px;
        background: var(--fds-colour-bg);
        color: var(--fds-colour-text);
    }

    main {
        max-width: 800px;
        margin: 0 auto;
    }

    section {
        margin-bottom: 40px;
    }

    h1 {
        margin-bottom: 32px;
    }

    h2 {
        border-bottom: 1px solid var(--fds-colour-border);
        padding-bottom: 8px;
        margin-top: 32px;
    }

    h3 {
        margin-top: 16px;
        margin-bottom: 8px;
        font-size: 14px;
        color: var(--fds-colour-text-subtlest);
    }

    .button-row {
        display: flex;
        gap: 12px;
        align-items: center;
        flex-wrap: wrap;
        margin-bottom: 12px;
    }
</style>

// native-ports/shared-core/ui/vue/src/App.vue
<script setup lang="ts">
import { ref } from "vue";
import DateRangeInput from "./components/date-range-input/DateRangeInput.vue";
import Button from "./components/button/Button.vue";
import type { DateRangeValue } from "./components/date-range-input/types";

const output1 = ref<DateRangeValue | null>(null);
const output2 = ref<DateRangeValue | null>(null);
const output3 = ref<DateRangeValue | null>(null);
const output4 = ref<DateRangeValue | null>(null);

function handleChange1(value: DateRangeValue) {
    output1.value = value;
}

function handleChange2(value: DateRangeValue) {
    output2.value = value;
}

function handleChange3(value: DateRangeValue) {
    output3.value = value;
}

function handleChange4(value: DateRangeValue) {
    output4.value = value;
}
</script>

<template>
    <div class="app">
        <header class="app-header">
            <h1>Vue 3 Port - Design System Components</h1>
            <p class="subtitle">
                Native port of React design system components
            </p>
        </header>

        <main class="examples">
            <!-- ============================== -->
            <!-- DateRangeInput Examples         -->
            <!-- ============================== -->
            <h2 class="section-title">DateRangeInput</h2>

            <!-- Example 1: Default -->
            <section class="example">
                <h3>1. Default</h3>
                <p class="description">
                    Empty date range input with Done/Cancel confirmation.
                </p>
                <DateRangeInput
                    label="Select date range"
                    @change="handleChange1"
                />
                <div v-if="output1" class="output">
                    <code>{{ JSON.stringify(output1) }}</code>
                </div>
            </section>

            <!-- Example 2: With initial values -->
            <section class="example">
                <h3>2. With Initial Values</h3>
                <p class="description">
                    Pre-filled with 2026-07-01 to 2026-07-15.
                </p>
                <DateRangeInput
                    label="Trip dates"
                    start-date="2026-07-01"
                    end-date="2026-07-15"
                    @change="handleChange2"
                />
                <div v-if="output2" class="output">
                    <code>{{ JSON.stringify(output2) }}</code>
                </div>
            </section>

            <!-- Example 3: Disabled -->
            <section class="example">
                <h3>3. Disabled</h3>
                <p class="description">
                    Input is disabled and cannot be interacted with.
                </p>
                <DateRangeInput
                    label="Locked range"
                    start-date="2026-07-01"
                    end-date="2026-07-15"
                    :disabled="true"
                    @change="handleChange3"
                />
                <div v-if="output3" class="output">
                    <code>{{ JSON.stringify(output3) }}</code>
                </div>
            </section>

            <!-- Example 4: Error state -->
            <section class="example">
                <h3>4. Error State</h3>
                <p class="description">Input displayed with error styling.</p>
                <DateRangeInput
                    label="Invalid range"
                    :error="true"
                    @change="handleChange4"
                />
                <div v-if="output4" class="output">
                    <code>{{ JSON.stringify(output4) }}</code>
                </div>
            </section>

            <!-- ============================== -->
            <!-- Button Examples                 -->
            <!-- ============================== -->
            <h2 class="section-title" style="margin-top: 32px">Button</h2>

            <!-- Style types -->
            <section class="example">
                <h3>Style Types</h3>
                <div class="button-row">
                    <Button style-type="default">Default</Button>
                    <Button style-type="secondary">Secondary</Button>
                    <Button style-type="light">Light</Button>
                    <Button style-type="link">Link</Button>
                </div>
            </section>

            <!-- Danger variants -->
            <section class="example">
                <h3>Danger Variants</h3>
                <div class="button-row">
                    <Button style-type="default" :danger="true">Default</Button>
                    <Button style-type="secondary" :danger="true"
                        >Secondary</Button
                    >
                    <Button style-type="light" :danger="true">Light</Button>
                    <Button style-type="link" :danger="true">Link</Button>
                </div>
            </section>

            <!-- Sizes -->
            <section class="example">
                <h3>Sizes</h3>
                <div class="button-row" style="align-items: center">
                    <Button size-type="large">Large</Button>
                    <Button size-type="default">Default</Button>
                    <Button size-type="small">Small</Button>
                </div>
            </section>

            <!-- Disabled -->
            <section class="example">
                <h3>Disabled</h3>
                <div class="button-row">
                    <Button :disabled="true">Disabled</Button>
                    <Button :disabled="true" :focusable-when-disabled="true"
                        >Focusable when disabled</Button
                    >
                </div>
            </section>

            <!-- Loading -->
            <section class="example">
                <h3>Loading</h3>
                <div class="button-row">
                    <Button :loading="true">Loading...</Button>
                    <Button :loading="true" style-type="secondary"
                        >Loading...</Button
                    >
                </div>
            </section>

            <!-- Icon + text -->
            <section class="example">
                <h3>Icon + Text</h3>
                <div class="button-row">
                    <Button>
                        <template #icon>
                            <svg
                                viewBox="0 0 24 24"
                                fill="none"
                                stroke="currentColor"
                                stroke-width="2"
                            >
                                <line x1="12" y1="5" x2="12" y2="19" />
                                <line x1="5" y1="12" x2="19" y2="12" />
                            </svg>
                        </template>
                        Add Item
                    </Button>
                    <Button icon-position="right" style-type="secondary">
                        <template #icon>
                            <svg
                                viewBox="0 0 24 24"
                                fill="none"
                                stroke="currentColor"
                                stroke-width="2"
                            >
                                <polyline points="9 6 15 12 9 18" />
                            </svg>
                        </template>
                        Next
                    </Button>
                </div>
            </section>

            <!-- Icon-only -->
            <section class="example">
                <h3>Icon Only</h3>
                <div class="button-row">
                    <Button aria-label="Add">
                        <template #icon>
                            <svg
                                viewBox="0 0 24 24"
                                fill="none"
                                stroke="currentColor"
                                stroke-width="2"
                            >
                                <line x1="12" y1="5" x2="12" y2="19" />
                                <line x1="5" y1="12" x2="19" y2="12" />
                            </svg>
                        </template>
                    </Button>
                    <Button style-type="secondary" aria-label="Settings">
                        <template #icon>
                            <svg
                                viewBox="0 0 24 24"
                                fill="none"
                                stroke="currentColor"
                                stroke-width="2"
                            >
                                <circle cx="12" cy="12" r="3" />
                                <path
                                    d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83-2.83l.06-.06A1.65 1.65 0 0 0 4.68 15a1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 2.83-2.83l.06.06A1.65 1.65 0 0 0 9 4.68a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 2.83l-.06.06A1.65 1.65 0 0 0 19.4 9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z"
                                />
                            </svg>
                        </template>
                    </Button>
                    <Button
                        style-type="light"
                        size-type="small"
                        aria-label="Close"
                    >
                        <template #icon>
                            <svg
                                viewBox="0 0 24 24"
                                fill="none"
                                stroke="currentColor"
                                stroke-width="2"
                            >
                                <line x1="18" y1="6" x2="6" y2="18" />
                                <line x1="6" y1="6" x2="18" y2="18" />
                            </svg>
                        </template>
                    </Button>
                </div>
            </section>
        </main>
    </div>
</template>

<style>
.app {
    max-width: 640px;
    margin: 0 auto;
    padding: 40px 24px 80px;
}

.app-header {
    margin-bottom: 40px;
}

.app-header h1 {
    font-size: 1.75rem;
    font-weight: 700;
    margin: 0 0 8px;
    color: var(--fds-colour-text);
}

.subtitle {
    color: var(--fds-colour-text-subtler);
    margin: 0;
    font-size: 14px;
}

.section-title {
    font-size: 1.375rem;
    font-weight: 700;
    margin: 0 0 24px;
    color: var(--fds-colour-text);
    padding-bottom: 8px;
    border-bottom: 1px solid var(--fds-colour-border);
}

.examples {
    display: flex;
    flex-direction: column;
    gap: 32px;
}

.example {
    display: flex;
    flex-direction: column;
    gap: 12px;
}

.example h3 {
    font-size: 1.125rem;
    font-weight: 600;
    margin: 0;
    color: var(--fds-colour-text);
}

.description {
    margin: 0;
    font-size: 14px;
    color: var(--fds-colour-text-subtler);
}

.output {
    margin-top: 4px;
    padding: 8px 12px;
    background: var(--fds-colour-bg);
    border: 1px solid var(--fds-colour-border);
    border-radius: var(--fds-radius-md);
}

.output code {
    font-size: 0.8125rem;
    color: var(--fds-colour-text-primary);
    word-break: break-all;
}

.button-row {
    display: flex;
    flex-wrap: wrap;
    gap: 12px;
}
</style>
